import type { MissionPlan } from "./mission-types";

export const CORE_MISSION_PLANS: readonly MissionPlan[] = [
  {
    levelId: "embed",
    role: "Cartógrafo de palabras",
    outcome: "Construye un mapa que permita buscar por parecido de significado.",
    bridge: "Un ID identifica una pieza; una lista de números aprendida permite compararla con otras.",
    concepts: [
      { concept: "Vector de embedding", plain: "Es una lista de números aprendidos que representa una palabra u otro contenido.", example: "En un mapa de juguete, gato tiene [0.8, 0.2] y perro [0.7, 0.3]; los valores reales se aprenden con ejemplos." },
      { concept: "Dimensión d", plain: "Es la cantidad de números que contiene cada lista del mapa.", example: "[0.8, 0.2] tiene 2 dimensiones, como una ficha con dos casillas numéricas." },
      { concept: "Similitud coseno", plain: "Compara la dirección de dos listas de números sin depender de su longitud.", example: "Las flechas [1, 1] y [2, 2] apuntan igual y tienen similitud 1, aunque una es más larga." },
      { concept: "Word2vec", plain: "Es una familia de métodos que aprende representaciones de palabras usando las palabras de alrededor.", example: "Al ver «el gato duerme» y «el perro duerme», encuentra contextos compartidos por gato y perro." },
      { concept: "Aritmética de vectores", plain: "Consiste en sumar o restar estas listas para explorar relaciones aprendidas.", example: "Sumar [1, 0] a [2, 3] mueve un punto a [3, 3]; que ese movimiento represente una relación útil depende del mapa." },
      { concept: "Espacio latente", plain: "Es el mapa numérico aprendido donde se sitúan las representaciones.", example: "Imagina una biblioteca cuya distribución se aprende leyendo libros, sin asignar de antemano un nombre a cada eje." },
    ],
    pipeline: {
      title: "Abre el mapa del significado",
      instruction: "Conecta las estaciones para encontrar contenido parecido a una consulta.",
      steps: [
        { label: "Recibir la consulta", detail: "El visitante escribe «animal que maúlla»; ese es el contenido que representaremos." },
        { label: "Crear su vector", detail: "El mismo modelo usado para los documentos transforma la consulta en una lista de números." },
        { label: "Comparar direcciones", detail: "Comparamos esa lista con los vectores guardados usando similitud coseno." },
        { label: "Mostrar los vecinos", detail: "Los resultados más parecidos aparecen primero; después podemos comprobar si realmente ayudan." },
      ],
    },
    sorter: {
      title: "Dos cajones del cartógrafo",
      instruction: "Envía cada ficha al cajón de etiquetas o al de representaciones comparables.",
      lanes: [{ label: "Solo identifica", description: "Una etiqueta permite localizar una ficha, pero su número no mide parecido." }, { label: "Representa contenido", description: "Una lista aprendida permite calcular semejanzas dentro del mismo mapa." }],
      items: [
        { label: "ID del token: 42", lane: 0, why: "42 es una etiqueta; el token 43 no tiene por qué parecerse." },
        { label: "Número de libro: 105", lane: 0, why: "El número de catálogo localiza el libro sin describir su tema." },
        { label: "Código del documento: A7", lane: 0, why: "El código distingue archivos, pero no representa sus significados." },
        { label: "Vector aprendido de «gato»", lane: 1, why: "Sus números pueden compararse con los de otras palabras del mismo modelo." },
        { label: "Vector de una consulta", lane: 1, why: "Permite buscar documentos representados por el mismo modelo." },
        { label: "Vector de un párrafo", lane: 1, why: "Resume numéricamente el contenido para compararlo con otros párrafos." },
      ],
    },
    build: {
      title: "Equipa una biblioteca por significado",
      brief: "Busca entre documentos por su contenido con un solo modelo de representaciones y un presupuesto de 8 fichas.",
      budget: 8,
      modules: [
        { label: "Modelo de embeddings", cost: 2, essential: true, why: "Convierte consultas y documentos al mismo mapa numérico." },
        { label: "Estante de vectores", cost: 2, essential: true, why: "Conserva la representación de cada documento para poder encontrarlo." },
        { label: "Comparador de similitud", cost: 2, essential: true, why: "Ordena los documentos por su parecido con la consulta." },
        { label: "Vista del texto original", cost: 1, essential: false, why: "Ayuda a revisar el resultado; una similitud alta no garantiza que sea pertinente." },
        { label: "Segundo idioma de prueba", cost: 2, essential: false, why: "Permite evaluar otra lengua si el modelo la admite, pero no crea el buscador básico." },
        { label: "Entrenar Word2vec propio", cost: 3, essential: false, why: "Es una forma de aprender vectores, aunque esta misión ya dispone de un modelo." },
      ],
    },
  },
  {
    levelId: "neuron",
    role: "Electricista del robot",
    outcome: "Arma una neurona que combine señales y decida cuánto activar una alarma.",
    bridge: "Como las pilas y estrellas aportaban energía distinta, cada señal puede tener un peso diferente.",
    concepts: [
      { concept: "Perceptrón", plain: "Es una neurona sencilla que combina entradas y compara el resultado con un umbral para decidir entre dos salidas.", example: "Una alarma de juguete se enciende cuando la suma de señales supera su límite." },
      { concept: "Pesos (w)", plain: "Son números que aumentan, reducen o invierten la aportación de cada entrada.", example: "Humo con peso 3 aporta tres veces más que una señal del mismo tamaño con peso 1." },
      { concept: "Sesgo (b)", plain: "Es una cantidad que se suma al total y desplaza cuándo responde la neurona.", example: "Añadir −2 hace que la alarma necesite más señal para alcanzar un resultado positivo." },
      { concept: "Función de activación", plain: "Es la regla que transforma la suma recibida en la salida de la neurona.", example: "Una regla puede apagar los valores negativos y dejar pasar los positivos." },
      { concept: "ReLU", plain: "Es una activación que devuelve cero para números negativos y conserva los positivos.", example: "Al recibir −3 entrega 0; al recibir 4 entrega 4." },
      { concept: "Sigmoide", plain: "Es una activación que comprime cualquier entrada a un valor entre cero y uno.", example: "En una salida preparada para estimar riesgo, 0.8 puede interpretarse como una probabilidad, pero requiere evaluación." },
      { concept: "Forward pass", plain: "Es recorrer la red desde las entradas hasta calcular la salida con sus pesos actuales.", example: "Entra humo=2, se multiplica por 3, se suma −2 y la activación recibe 4." },
    ],
    pipeline: {
      title: "Enciende la alarma paso a paso",
      instruction: "Cablea las estaciones para que una señal llegue a la salida.",
      steps: [
        { label: "Leer sensores", detail: "Recibe las medidas de humo y calor como dos números." },
        { label: "Aplicar pesos", detail: "Multiplica cada medida por el peso de su cable para calcular su aportación." },
        { label: "Sumar y desplazar", detail: "Junta las aportaciones y suma el sesgo para obtener un único total." },
        { label: "Activar la salida", detail: "La función elegida transforma ese total en la señal de alarma." },
      ],
    },
    sorter: {
      title: "Mesa de lecturas y mesa de ajustes",
      instruction: "Separa los números que llegan del mundo de los ajustes que conserva la neurona.",
      lanes: [{ label: "Lectura de entrada", description: "Cambia con el ejemplo que recibe el robot." }, { label: "Ajuste aprendido", description: "Es un peso o sesgo que puede cambiar durante el entrenamiento." }],
      items: [
        { label: "Humo medido: 2", lane: 0, why: "Es lo que observa el sensor en este momento, no un peso del modelo." },
        { label: "Calor medido: 5", lane: 0, why: "Es una entrada nueva que puede variar entre habitaciones." },
        { label: "Luz medida: 1", lane: 0, why: "Describe la escena que se está procesando." },
        { label: "Peso del humo: 3", lane: 1, why: "Regula cuánto influye la lectura de humo en la suma." },
        { label: "Peso del calor: 2", lane: 1, why: "Es parte de la configuración de la neurona, no una lectura del termómetro." },
        { label: "Sesgo de alarma: −2", lane: 1, why: "Desplaza el total y puede aprenderse junto con los pesos." },
      ],
    },
    build: {
      title: "Monta una neurona con ReLU",
      brief: "Construye la ruta completa desde los sensores hasta una salida ReLU; las piezas de lujo pueden esperar.",
      budget: 8,
      modules: [
        { label: "Conector de entradas", cost: 1, essential: true, why: "Da acceso a los números de los sensores." },
        { label: "Multiplicadores con pesos", cost: 2, essential: true, why: "Permiten que cada sensor influya de forma distinta." },
        { label: "Sumador con sesgo", cost: 2, essential: true, why: "Reúne las señales y aplica el desplazamiento antes de activar." },
        { label: "Puerta ReLU", cost: 1, essential: true, why: "Cumple la salida de esta misión: cero si el total es negativo." },
        { label: "Panel de señales", cost: 2, essential: false, why: "Hace visibles los cálculos, aunque la neurona puede funcionar sin pantalla." },
        { label: "Otra capa de neuronas", cost: 3, essential: false, why: "Añade capacidad a una red, pero aún no hace falta para construir esta neurona." },
      ],
    },
  },
  {
    levelId: "backprop",
    role: "Detective del error",
    outcome: "Sigue una equivocación hacia atrás y localiza qué ajustes pueden reducirla.",
    bridge: "Ya calculaste una salida; ahora compararás ese resultado con la meta para aprender de la diferencia.",
    concepts: [
      { concept: "Forward pass", plain: "Es calcular la predicción avanzando por las capas con los ajustes actuales.", example: "Una foto recorre la red y produce una puntuación de 0.3 para «gato»." },
      { concept: "Función de pérdida", plain: "Es una regla que convierte la diferencia entre la predicción y la meta en un número de error.", example: "En un juego de puntería podemos elevar al cuadrado la distancia entre tiro y diana." },
      { concept: "Gradiente", plain: "Es una lista que indica cómo cambiaría el error si movieras ligeramente cada ajuste.", example: "Si subir un peso aumenta el error, el gradiente señala que conviene probar a bajarlo." },
      { concept: "Regla de la cadena", plain: "Permite combinar los efectos de varias operaciones conectadas para saber cómo influye una entrada en el resultado final.", example: "Si una palanca duplica un movimiento y la siguiente lo triplica, el efecto conjunto se multiplica por seis." },
      { concept: "Backpropagation", plain: "Es calcular los gradientes desde la salida hacia las primeras capas aprovechando resultados ya obtenidos.", example: "Sigues el cable de una alarma equivocada hacia atrás para calcular cuánto influyó cada ajuste." },
      { concept: "Vanishing gradient", plain: "Ocurre cuando la señal de cambio se hace tan pequeña al retroceder que algunas capas apenas aprenden.", example: "Un mensaje que se reduce a la mitad en cada estación acaba llegando como un susurro." },
    ],
    pipeline: {
      title: "Rastrea una predicción equivocada",
      instruction: "Ordena la ruta que convierte una predicción en indicaciones para corregir los pesos.",
      steps: [
        { label: "Hacer una predicción", detail: "La entrada recorre la red y se guardan los resultados intermedios necesarios." },
        { label: "Medir la pérdida", detail: "Compara la salida con la respuesta esperada para obtener un error." },
        { label: "Retroceder por las capas", detail: "Usa la regla de la cadena para calcular cómo contribuye cada ajuste al error." },
        { label: "Entregar los gradientes", detail: "El optimizador recibe estas indicaciones y podrá actualizar los pesos." },
      ],
    },
    sorter: {
      title: "Trenes de ida y de regreso",
      instruction: "Despacha cada paquete en el sentido en que viaja durante este entrenamiento.",
      lanes: [{ label: "Ida: calcular", description: "Lleva entradas y resultados hacia la predicción." }, { label: "Regreso: atribuir error", description: "Lleva información de cambio desde la pérdida hacia los pesos." }],
      items: [
        { label: "Entrada hacia la primera capa", lane: 0, why: "La predicción empieza procesando el ejemplo recibido." },
        { label: "Activación hacia la siguiente capa", lane: 0, why: "La salida de una capa alimenta a la siguiente en el recorrido de ida." },
        { label: "Predicción hacia el medidor de pérdida", lane: 0, why: "Primero necesitamos la salida para compararla con la meta." },
        { label: "Gradiente de la última capa", lane: 1, why: "Se calcula a partir de cómo cambia la pérdida cerca de la salida." },
        { label: "Señal hacia una capa anterior", lane: 1, why: "La regla de la cadena permite seguir el efecto hacia atrás." },
        { label: "Gradiente de un peso inicial", lane: 1, why: "Resume cómo ese peso temprano influye en el error final." },
      ],
    },
    build: {
      title: "Equipa el laboratorio de gradientes",
      brief: "Calcula indicaciones de cambio para una red ya construida; otro taller se encargará de aplicar las actualizaciones.",
      budget: 7,
      modules: [
        { label: "Registro de operaciones", cost: 2, essential: true, why: "Conserva las conexiones y valores necesarios para recorrer el cálculo al revés." },
        { label: "Medidor de pérdida", cost: 2, essential: true, why: "Define qué error queremos reducir y desde dónde comienza el regreso." },
        { label: "Motor de regla de la cadena", cost: 2, essential: true, why: "Calcula los gradientes de los ajustes conectados a la pérdida." },
        { label: "Mapa de gradientes", cost: 1, essential: false, why: "Ayuda a detectar señales muy pequeñas o muy grandes, aunque no las calcula por sí solo." },
        { label: "Optimizador Adam", cost: 3, essential: false, why: "Puede aplicar los gradientes después; calcularlos y actualizar pesos son tareas distintas." },
        { label: "Generador de nuevas imágenes", cost: 2, essential: false, why: "Añade ejemplos de entrenamiento, pero no permite atribuir el error de los que ya tienes." },
      ],
    },
  },
  {
    levelId: "grad",
    role: "Piloto del descenso",
    outcome: "Prepara pasos de aprendizaje que acerquen al robot a un error menor sin gastar todo el presupuesto.",
    bridge: "El gradiente señala cómo cambia el error; el optimizador decide cuánto mover cada peso.",
    concepts: [
      { concept: "Gradient Descent", plain: "Es actualizar los pesos en sentido contrario al aumento local del error.", example: "Si un pequeño paso a la derecha sube la cuesta, pruebas un paso corto a la izquierda." },
      { concept: "Learning rate", plain: "Es el tamaño que das a los pasos de actualización.", example: "Pasos enormes pueden saltar de un lado del valle al otro; pasos pequeños tardan más." },
      { concept: "Batch / Mini-batch", plain: "Es el grupo de ejemplos con el que calculas una actualización del entrenamiento.", example: "Antes de mover los pesos, reúnes la señal de ocho fotos en lugar de mirar una sola." },
      { concept: "Momentum", plain: "Conserva parte de la dirección de pasos anteriores para suavizar los cambios de rumbo.", example: "Una pelota que avanza por el valle mantiene impulso aunque encuentre pequeñas irregularidades." },
      { concept: "Adam", plain: "Es un optimizador que usa el historial de los gradientes para adaptar los pasos de cada peso.", example: "Dos mandos reciben pasos distintos si uno cambia violentamente y el otro permanece estable." },
      { concept: "Weight decay", plain: "Es una técnica que empuja los pesos hacia valores más pequeños durante el entrenamiento.", example: "Un pequeño tirón hacia cero evita que un mando siga creciendo sin ninguna resistencia." },
    ],
    pipeline: {
      title: "Completa una vuelta de entrenamiento",
      instruction: "Monta un ciclo que use ejemplos, mida su error y ajuste la red.",
      steps: [
        { label: "Reunir un mini-batch", detail: "Selecciona un grupo de ejemplos para esta actualización." },
        { label: "Calcular su pérdida", detail: "Predice las respuestas y combina sus errores en una medida del grupo." },
        { label: "Obtener gradientes", detail: "Retropropaga esa pérdida para conocer la dirección local del cambio." },
        { label: "Actualizar los pesos", detail: "El optimizador usa los gradientes y el tamaño de paso; después comienza otro ciclo." },
      ],
    },
    sorter: {
      title: "Mochila del paso y cuaderno de resultados",
      instruction: "Organiza los ajustes que eliges y las mediciones que observas para decidir cómo entrenar.",
      lanes: [{ label: "Ajuste del entrenamiento", description: "Lo configuras para dirigir las actualizaciones." }, { label: "Medición observada", description: "Se obtiene al ejecutar o evaluar el entrenamiento." }],
      items: [
        { label: "Tamaño de paso: 0.01", lane: 0, why: "Es una elección del learning rate, no el error que obtuviste." },
        { label: "Grupo de 8 ejemplos", lane: 0, why: "El tamaño del mini-batch determina cuántos ejemplos usas en cada paso." },
        { label: "Activar weight decay", lane: 0, why: "Es una regla elegida para moderar el tamaño de los pesos." },
        { label: "Pérdida medida: 0.4", lane: 1, why: "Es el resultado de comparar las predicciones con sus metas." },
        { label: "Tiempo por actualización", lane: 1, why: "Se mide mientras corre el entrenamiento y ayuda a estimar su costo." },
        { label: "Aciertos en ejemplos nuevos", lane: 1, why: "La evaluación muestra si lo aprendido sirve fuera de los ejemplos de entrenamiento." },
      ],
    },
    build: {
      title: "Ajusta el piloto automático",
      brief: "La red ya produce gradientes: instala un entrenamiento básico por mini-batches con pasos controlables.",
      budget: 8,
      modules: [
        { label: "Bandeja de mini-batches", cost: 2, essential: true, why: "Entrega los grupos de ejemplos con los que trabajarás." },
        { label: "Actualizador por gradiente", cost: 2, essential: true, why: "Convierte la señal de cambio en nuevos valores de los pesos." },
        { label: "Control de learning rate", cost: 2, essential: true, why: "Permite ajustar cuánto se mueve el modelo en cada actualización." },
        { label: "Memoria de momentum", cost: 1, essential: false, why: "Puede suavizar el recorrido, pero el descenso básico también funciona sin impulso." },
        { label: "Resorte de weight decay", cost: 2, essential: false, why: "Puede ayudar a regularizar los pesos; no sustituye los ejemplos ni los gradientes." },
        { label: "Panel de curvas", cost: 2, essential: false, why: "Permite observar el progreso y detectar oscilaciones durante los ensayos." },
      ],
    },
  },
  {
    levelId: "attn",
    role: "Operador del faro de atención",
    outcome: "Conecta una consulta con las pistas que ayudan a interpretar una frase.",
    bridge: "Las palabras ya tienen vectores; ahora pueden buscar información unas en otras.",
    concepts: [
      { concept: "Query", plain: "Es la representación de lo que una posición busca en las demás.", example: "Al leer «ella», imagina una ficha que busca pistas sobre la persona mencionada antes." },
      { concept: "Key", plain: "Es la representación con la que cada posición se ofrece para ser comparada con una consulta.", example: "Como la etiqueta de un cajón, ayuda a decidir si allí hay información pertinente." },
      { concept: "Value", plain: "Es la información que una posición aporta a la mezcla después de recibir atención.", example: "La etiqueta ayuda a elegir el cajón; el contenido de dentro es lo que finalmente recuperas." },
      { concept: "Scaled Dot-Product", plain: "Compara consultas y claves y ajusta el tamaño de sus puntuaciones según la dimensión de sus vectores.", example: "Es un marcador de coincidencias calibrado para que añadir más casillas numéricas no infle tanto los resultados." },
      { concept: "Softmax", plain: "Transforma las puntuaciones permitidas en pesos positivos que juntos suman uno.", example: "Puede repartir la atención como 0.7 para Ana, 0.2 para libro y 0.1 para mesa." },
      { concept: "Multi-Head Attention", plain: "Combina varias búsquedas de atención hechas con representaciones diferentes.", example: "Varios faros miran la misma frase desde lentes distintas y luego reúnen sus hallazgos." },
      { concept: "Causal mask", plain: "Impide que una posición use tokens que todavía no han ocurrido en una secuencia generada.", example: "Al completar «el gato», una cortina tapa la palabra siguiente para que no puedas copiarla." },
    ],
    pipeline: {
      title: "Sigue una pista en la frase",
      instruction: "Conecta el recorrido desde las representaciones hasta la mezcla de información.",
      steps: [
        { label: "Crear consultas, claves y valores", detail: "Transforma cada representación en lo que busca, cómo se anuncia y lo que aporta." },
        { label: "Comparar y aplicar la máscara", detail: "Calcula puntuaciones ajustadas y bloquea las posiciones que no se pueden consultar." },
        { label: "Repartir la atención", detail: "Softmax convierte las puntuaciones permitidas en pesos que suman uno." },
        { label: "Mezclar los valores", detail: "Multiplica cada contenido por su peso y suma las aportaciones." },
      ],
    },
    sorter: {
      title: "Cortina del futuro",
      instruction: "El robot genera texto de izquierda a derecha: deja pasar lo disponible y tapa lo que aún no existe.",
      lanes: [{ label: "Puede consultar", description: "Información presente en el contexto hasta esta posición." }, { label: "Debe quedar tapado", description: "Tokens posteriores que aún no se han generado." }],
      items: [
        { label: "Primer token del mensaje", lane: 0, why: "Ya forma parte del contexto recibido." },
        { label: "Token justo anterior", lane: 0, why: "Ocurrió antes y la atención causal puede utilizarlo." },
        { label: "Token en la posición actual", lane: 0, why: "En la atención causal habitual, una posición también puede consultarse a sí misma." },
        { label: "Siguiente token por generar", lane: 1, why: "Todavía no está disponible: usarlo revelaría la respuesta." },
        { label: "Última palabra futura", lane: 1, why: "Un final conocido solo después de generar no puede ayudar en este paso." },
        { label: "Token dos pasos por delante", lane: 1, why: "La cortina causal bloquea todas las posiciones posteriores, no solo la siguiente." },
      ],
    },
    build: {
      title: "Construye un faro causal",
      brief: "Monta atención para un robot que escribe de izquierda a derecha; el taller ya te entrega consultas, claves y valores.",
      budget: 8,
      modules: [
        { label: "Comparador ajustado", cost: 2, essential: true, why: "Calcula cuánto coinciden las consultas con las claves." },
        { label: "Cortina causal", cost: 1, essential: true, why: "Bloquea el futuro durante el cálculo de esta atención." },
        { label: "Repartidor softmax", cost: 1, essential: true, why: "Convierte las puntuaciones disponibles en pesos de mezcla." },
        { label: "Mezclador de valores", cost: 2, essential: true, why: "Obtiene el contenido final sumando las aportaciones ponderadas." },
        { label: "Otro faro de atención", cost: 2, essential: false, why: "Añade otra perspectiva, aunque un solo faro basta para esta primera construcción." },
        { label: "Mapa de pesos en colores", cost: 1, essential: false, why: "Ayuda a observar la mezcla; los colores por sí solos no explican todo el razonamiento del modelo." },
      ],
    },
  },
  {
    levelId: "trans",
    role: "Arquitecto de bloques",
    outcome: "Ensambla un bloque que mezcle contexto, transforme información y conserve una ruta de entrada.",
    bridge: "La atención es una pieza del motor; al combinarla con otras piezas obtenemos un bloque transformer.",
    concepts: [
      { concept: "Encoder/Decoder", plain: "Son diseños de bloques que pueden representar una entrada o producir una secuencia, con reglas distintas para consultar el contexto.", example: "En una traducción, un encoder representa la frase recibida y un decoder va construyendo la salida." },
      { concept: "Bloque transformer", plain: "Es un módulo que combina atención, transformación por posición y rutas que estabilizan el cálculo.", example: "Piensa en un piso de fábrica donde las fichas comparten información y después pasan por su propio taller." },
      { concept: "FFN", plain: "Es una pequeña red que transforma cada posición por separado después de recibir su representación.", example: "Todas las fichas usan la misma máquina, pero cada una entra con sus propios números." },
      { concept: "LayerNorm", plain: "Ajusta la escala de los números de una representación para que el cálculo sea más manejable.", example: "Como calibrar los medidores de una ficha antes de enviarla al siguiente taller." },
      { concept: "Residual connection", plain: "Es una ruta que suma la entrada original a la transformación calculada.", example: "Conservas la ficha anterior y le añades una actualización en vez de reemplazarla completamente." },
      { concept: "Stacking", plain: "Es conectar varios bloques para que cada uno procese el resultado del anterior.", example: "El segundo piso recibe lo que elaboró el primero y prepara la entrada del tercero." },
      { concept: "Pre-norm vs Post-norm", plain: "Distingue si la normalización se aplica antes de una transformación o después de sumarla con su entrada.", example: "Puedes calibrar la ficha antes del taller o calibrar el resultado combinado al salir." },
    ],
    pipeline: {
      title: "Arma un piso de la fábrica",
      instruction: "Sigue una versión pre-norm simplificada de un bloque: cada estación necesita la salida anterior.",
      steps: [
        { label: "Guardar entrada y normalizar", detail: "Reserva una copia y calibra la representación que entrará a la atención." },
        { label: "Aplicar atención y sumar", detail: "Mezcla el contexto y añade el resultado a la copia reservada." },
        { label: "Guardar de nuevo y normalizar", detail: "Reserva la nueva representación y prepara su escala para la FFN." },
        { label: "Aplicar FFN y sumar", detail: "Transforma cada posición y suma la copia para entregar el resultado al siguiente bloque." },
      ],
    },
    sorter: {
      title: "Taller compartido y taller por ficha",
      instruction: "Dirige las operaciones según necesiten relacionar posiciones o trabajen sobre una sola ficha.",
      lanes: [{ label: "Relaciona posiciones", description: "Combina o compara información de distintos lugares del contexto." }, { label: "Trabaja por posición", description: "Opera sobre los números de cada ficha sin mezclar otras posiciones directamente." }],
      items: [
        { label: "Comparar query con otras keys", lane: 0, why: "La búsqueda calcula relaciones entre la posición que pregunta y las que pueden responder." },
        { label: "Mezclar values de la frase", lane: 0, why: "La atención reúne contenido procedente de varias posiciones." },
        { label: "Consultar la frase de entrada al traducir", lane: 0, why: "Esta atención conecta posiciones de la salida con posiciones de la entrada." },
        { label: "Transformar una ficha con FFN", lane: 1, why: "La FFN aplica la misma red por separado a cada posición." },
        { label: "Normalizar los números de una ficha", lane: 1, why: "LayerNorm trabaja sobre las características de esa representación." },
        { label: "Sumar entrada y actualización de una ficha", lane: 1, why: "La conexión residual combina las dos versiones correspondientes a la misma posición." },
      ],
    },
    build: {
      title: "Entrega un bloque pre-norm",
      brief: "Construye un bloque con atención, FFN, normalización y rutas residuales antes de añadir más pisos.",
      budget: 9,
      modules: [
        { label: "Sala de atención", cost: 2, essential: true, why: "Permite que las posiciones intercambien información del contexto." },
        { label: "Taller FFN", cost: 2, essential: true, why: "Transforma por separado la representación de cada posición." },
        { label: "Normalizadores", cost: 1, essential: true, why: "Calibran las representaciones antes de los dos talleres en este diseño pre-norm." },
        { label: "Puentes residuales", cost: 2, essential: true, why: "Conservan las rutas que suman cada entrada a su actualización." },
        { label: "Otro bloque completo", cost: 3, essential: false, why: "Apilar bloques añade profundidad, pero primero necesitamos terminar este bloque." },
        { label: "Ventanas de inspección", cost: 1, essential: false, why: "Permiten observar las representaciones intermedias durante el juego." },
      ],
    },
  },
  {
    levelId: "gen",
    role: "DJ de palabras",
    outcome: "Convierte las puntuaciones del transformer en una continuación controlable, token a token.",
    bridge: "El transformer entrega puntuaciones; ahora aprenderás a convertirlas en una secuencia sin copiar una respuesta ya escrita.",
    concepts: [
      { concept: "Autoregresión", plain: "Es generar una pieza, añadirla al contexto y usar todo lo disponible para producir la siguiente.", example: "El robot escribe «La», la relee junto al prompt y después decide si continúa con «luna», «casa» u otra pieza." },
      { concept: "Logits", plain: "Son las puntuaciones crudas que el modelo asigna a cada token posible antes de convertirlas en probabilidades.", example: "Si «gato» recibe 4 y «avión» recibe 1, el primero parte con ventaja, pero esos números todavía no suman uno." },
      { concept: "Softmax con temperature", plain: "Convierte logits en probabilidades y usa la temperatura para concentrarlas o repartirlas más.", example: "Una temperatura baja vuelve favorita a la ficha líder; una más alta permite que fichas cercanas entren más veces en el sorteo." },
      { concept: "Top-k", plain: "Conserva solo los k tokens con mayor probabilidad antes de elegir el siguiente.", example: "Con top-k=3, la ruleta se queda únicamente con las tres fichas mejor puntuadas." },
      { concept: "Top-p (nucleus)", plain: "Conserva el grupo más pequeño de tokens cuya probabilidad acumulada alcanza un límite p.", example: "Con top-p=0.9 pueden entrar dos candidatos muy claros o diez candidatos parecidos, según la forma de la distribución." },
      { concept: "Beam search", plain: "Mantiene varias continuaciones candidatas y expande las que acumulan mejor puntuación.", example: "Como explorar tres pasillos a la vez y abandonar los recorridos que van quedando demasiado atrás." },
      { concept: "KV cache", plain: "Guarda cálculos de atención de tokens anteriores para no repetirlos en cada paso de generación.", example: "El cocinero conserva los ingredientes ya preparados y solo procesa la nueva ficha que acaba de llegar." },
    ],
    pipeline: {
      title: "Pon en marcha la máquina de historias",
      instruction: "Conecta las estaciones que convierten una salida numérica en el siguiente token y repiten el ciclo.",
      steps: [
        { label: "Leer los logits", detail: "El transformer entrega una puntuación para cada ficha del vocabulario." },
        { label: "Moldear la distribución", detail: "Aplica temperatura y, si corresponde, top-k o top-p antes del sorteo." },
        { label: "Elegir y añadir un token", detail: "Selecciona una ficha con la distribución resultante y colócala al final del texto." },
        { label: "Guardar y repetir", detail: "Actualiza el KV cache y usa la secuencia ampliada para calcular el próximo paso." },
      ],
    },
    sorter: {
      title: "Cabina creativa y sala de máquinas",
      instruction: "Separa los controles que cambian las opciones del sorteo de los mecanismos que recorren o aceleran la secuencia.",
      lanes: [{ label: "Moldea la elección", description: "Cambia qué candidatos pueden participar o cuánta ventaja conserva cada uno." }, { label: "Construye la secuencia", description: "Organiza candidatos completos o evita repetir trabajo entre pasos." }],
      items: [
        { label: "Temperatura 0.3", lane: 0, why: "Concentra más probabilidad en las opciones que ya tenían logits altos." },
        { label: "Top-k de 5", lane: 0, why: "Recorta la ruleta a cinco tokens antes de muestrear." },
        { label: "Top-p de 0.9", lane: 0, why: "Ajusta dinámicamente cuántos tokens sobreviven según su probabilidad acumulada." },
        { label: "Añadir la ficha elegida al contexto", lane: 1, why: "Ese paso autoregresivo crea la secuencia que condicionará la siguiente elección." },
        { label: "Conservar tres beams", lane: 1, why: "Mantiene varias continuaciones completas mientras busca la mejor puntuación acumulada." },
        { label: "Reutilizar keys y values anteriores", lane: 1, why: "El KV cache acelera el siguiente paso sin cambiar su distribución por sí mismo." },
      ],
    },
    build: {
      title: "Configura un narrador token a token",
      brief: "Entrega una continuación variada pero controlada y evita recalcular todo el prefijo en cada ficha.",
      budget: 8,
      modules: [
        { label: "Lector de logits", cost: 1, essential: true, why: "Recibe las puntuaciones desde las que empieza cada elección." },
        { label: "Control de temperatura", cost: 1, essential: true, why: "Permite ajustar cuán concentrada queda la distribución de candidatos." },
        { label: "Filtro top-p", cost: 2, essential: true, why: "Recorta la cola con un límite que se adapta a cada paso." },
        { label: "Bucle autoregresivo con KV cache", cost: 2, essential: true, why: "Añade cada token y reutiliza los cálculos anteriores para continuar." },
        { label: "Explorador beam search", cost: 3, essential: false, why: "Sirve en búsquedas concretas, pero no es obligatorio para un narrador por muestreo." },
        { label: "Selector de rimas", cost: 2, essential: false, why: "Puede orientar un estilo particular, aunque no construye el mecanismo básico de generación." },
      ],
    },
  },
  {
    levelId: "hardware",
    role: "Jefe de pista del centro de cómputo",
    outcome: "Diseña una estación que alimente matrices al acelerador sin desperdiciar precisión, memoria ni energía.",
    bridge: "Generar cada token exige muchas multiplicaciones y mover muchos números; ahora entrarás a la máquina física que hace ese trabajo.",
    concepts: [
      { concept: "GPU vs CPU", plain: "Una CPU destaca siguiendo pocas tareas complejas y una GPU ejecutando muchas operaciones numéricas parecidas en paralelo.", example: "Un chef experto resuelve pedidos distintos; una gran brigada corta miles de cubos iguales al mismo tiempo." },
      { concept: "FLOPS", plain: "Es una medida de cuántas operaciones con números de punto flotante puede realizar un sistema por segundo.", example: "Cuenta la velocidad máxima del motor matemático, aunque una carretera lenta de memoria puede impedir alcanzarla." },
      { concept: "Mixed precision (BF16, FP16)", plain: "Es combinar formatos numéricos pequeños para acelerar cálculos con copias o acumulaciones más precisas cuando hacen falta.", example: "Usas cajas compactas BF16 para transportar muchos valores y una libreta más detallada para conservar actualizaciones delicadas." },
      { concept: "Memory bandwidth", plain: "Es la cantidad de datos que puede viajar entre memoria y procesadores en un tiempo determinado.", example: "Aunque haya mil cocineros, trabajan despacio si la puerta de la despensa solo deja pasar una bandeja." },
      { concept: "HBM", plain: "Es memoria de gran ancho de banda colocada muy cerca del acelerador para mover datos con rapidez.", example: "Es una despensa apilada junto a la cocina en vez de un almacén al otro lado de la ciudad." },
      { concept: "TPU", plain: "Es un acelerador especializado en operaciones de tensores diseñado para cargas de aprendizaje automático.", example: "Como una fábrica construida alrededor de cintas para multiplicar matrices en lugar de una herramienta de uso general." },
      { concept: "Training cost", plain: "Es el conjunto de tiempo, energía, hardware y dinero consumido al entrenar y repetir experimentos.", example: "Duplicar tarjetas no siempre divide la factura a la mitad porque también hay comunicación, espera y pruebas fallidas." },
    ],
    pipeline: {
      title: "Despacha un lote por el acelerador",
      instruction: "Organiza el viaje de los tensores desde el lote hasta una actualización sin atascar la estación.",
      steps: [
        { label: "Preparar tensores", detail: "Agrupa ejemplos en formas regulares que el acelerador pueda procesar en paralelo." },
        { label: "Elegir precisión", detail: "Usa BF16 o FP16 donde sea seguro y conserva mayor precisión para operaciones sensibles." },
        { label: "Mover y calcular", detail: "Alimenta datos desde HBM a los núcleos mientras ejecutan multiplicaciones de matrices." },
        { label: "Medir la estación", detail: "Registra tiempo, memoria, utilización y energía para conocer el costo real del paso." },
      ],
    },
    sorter: {
      title: "¿Motor ocupado o despensa lenta?",
      instruction: "Envía cada carga al cuello de botella que probablemente limita su velocidad.",
      lanes: [{ label: "Limitada por cómputo", description: "El acelerador pasa más tiempo haciendo operaciones que esperando datos." }, { label: "Limitada por memoria", description: "Mover o almacenar datos pesa más que las operaciones realizadas con ellos." }],
      items: [
        { label: "Matrices grandes de un lote de entrenamiento", lane: 0, why: "Las multiplicaciones densas grandes pueden mantener ocupadas muchas unidades de cálculo." },
        { label: "Cálculo de gradientes de una capa ancha", lane: 0, why: "Requiere muchas operaciones paralelas sobre tensores de gran tamaño." },
        { label: "Entrenamiento con lotes bien agrupados", lane: 0, why: "Reutiliza datos lo suficiente para acercarse más al límite de FLOPS." },
        { label: "Decode de un usuario, token a token", lane: 1, why: "Cada paso suele leer muchos pesos para producir muy poco trabajo por dato movido." },
        { label: "KV cache de un contexto muy largo", lane: 1, why: "Leer y conservar claves y valores puede consumir gran parte del ancho de banda y la capacidad." },
        { label: "Cargar pesos que casi no se reutilizan", lane: 1, why: "El acelerador espera a que la memoria entregue grandes cantidades de datos." },
      ],
    },
    build: {
      title: "Equipa una estación de entrenamiento",
      brief: "Procesa lotes de matrices con precisión mixta y confirma dónde se gasta el presupuesto físico.",
      budget: 8,
      modules: [
        { label: "Acelerador GPU o TPU", cost: 2, essential: true, why: "Ejecuta en paralelo las operaciones tensoriales del entrenamiento." },
        { label: "Memoria HBM", cost: 2, essential: true, why: "Mantiene pesos, activaciones y lotes cerca del acelerador con alto ancho de banda." },
        { label: "Motor de precisión mixta", cost: 1, essential: true, why: "Reduce memoria y tiempo sin renunciar a los cálculos que necesitan más rango." },
        { label: "Medidor de utilización y costo", cost: 1, essential: true, why: "Distingue capacidad teórica de rendimiento y gasto realmente obtenidos." },
        { label: "CPU de coordinación adicional", cost: 2, essential: false, why: "Puede preparar datos y tareas, pero otra CPU no reemplaza el trabajo tensorial del acelerador." },
        { label: "Panel luminoso del rack", cost: 2, essential: false, why: "Hace visible el estado, aunque no aumenta FLOPS ni ancho de banda." },
      ],
    },
  },
  {
    levelId: "scaling",
    role: "Estratega de la granja de entrenamiento",
    outcome: "Reparte un presupuesto fijo entre modelo y datos usando mediciones en lugar de apostar a ciegas.",
    bridge: "Ya conoces el costo del hardware; ahora decidirás qué tamaño de modelo y cuántos datos aprovechan mejor ese cómputo.",
    concepts: [
      { concept: "Kaplan scaling", plain: "Es un conjunto temprano de relaciones empíricas que conectó la pérdida con parámetros, datos y cómputo al escalar modelos de lenguaje.", example: "Al poner resultados de varios modelos en una gráfica logarítmica, los puntos siguieron líneas bastante regulares." },
      { concept: "Chinchilla optimal", plain: "Es la idea de equilibrar el crecimiento del modelo con suficientes tokens de entrenamiento para aprovechar un presupuesto fijo.", example: "Con el mismo combustible, un motor algo menor que practica con muchas más vueltas puede superar a uno enorme poco entrenado." },
      { concept: "Compute-optimal", plain: "Describe la combinación de tamaño y datos que obtiene la menor pérdida posible dentro de un límite de cálculo.", example: "No busca el modelo más grande que cabe, sino el reparto que produce el mejor resultado con las mismas horas de acelerador." },
      { concept: "Emergent abilities", plain: "Son capacidades que parecen aparecer al cruzar cierta escala, aunque el salto observado puede depender de cómo se mida.", example: "Una puntuación de aprobado puede saltar de cero a uno aun cuando la probabilidad de responder bien haya mejorado poco a poco." },
      { concept: "Power law", plain: "Es una relación donde una cantidad cambia como una potencia de otra y forma una recta al usar escalas logarítmicas.", example: "Cada multiplicación del cómputo reduce la pérdida por una fracción predecible, no por una cantidad fija." },
      { concept: "Bitter lesson", plain: "Es la observación de que los métodos generales capaces de aprovechar más cómputo suelen superar con el tiempo a reglas humanas muy específicas.", example: "Un sistema que aprende y busca con más recursos termina adelantando a un gran recetario escrito para cada caso." },
    ],
    pipeline: {
      title: "Planea el entrenamiento sin quemar la granja",
      instruction: "Usa pequeñas mediciones para elegir el reparto de recursos antes de lanzar la carrera grande.",
      steps: [
        { label: "Fijar presupuesto y meta", detail: "Define el cómputo disponible y la pérdida o tarea con la que compararás diseños." },
        { label: "Correr pilotos", detail: "Entrena modelos pequeños con distintos tamaños y cantidades de datos bajo condiciones comparables." },
        { label: "Ajustar la tendencia", detail: "Usa los resultados para estimar una power law y revisar dónde deja de describir los datos." },
        { label: "Elegir y verificar", detail: "Selecciona el reparto compute-optimal y reserva una evaluación final para comprobar la predicción." },
      ],
    },
    sorter: {
      title: "Tablero de recursos y tablero de resultados",
      instruction: "Separa lo que inviertes antes de entrenar de lo que observas al medir el modelo.",
      lanes: [{ label: "Recurso de escala", description: "Forma parte del tamaño o del presupuesto consumido durante el entrenamiento." }, { label: "Resultado medido", description: "Describe el comportamiento obtenido después de usar esos recursos." }],
      items: [
        { label: "Cantidad de parámetros", lane: 0, why: "Define capacidad del modelo y participa en el costo de cada paso." },
        { label: "Tokens de entrenamiento", lane: 0, why: "Indica cuántos ejemplos de texto alimentan el aprendizaje." },
        { label: "FLOPs disponibles", lane: 0, why: "Marca el límite total de operaciones que puede gastar el experimento." },
        { label: "Pérdida de validación", lane: 1, why: "Se observa en datos separados para comparar cuánto generaliza cada diseño." },
        { label: "Aciertos en una capacidad", lane: 1, why: "Es un efecto medido y su aparente salto puede depender de la métrica elegida." },
        { label: "Calidad con el mismo cómputo", lane: 1, why: "Permite decidir cuál reparto de parámetros y datos usó mejor el presupuesto." },
      ],
    },
    build: {
      title: "Construye un laboratorio de escalado",
      brief: "Elige un diseño para comparar pilotos y recomendar una carrera grande sin exceder ocho fichas.",
      budget: 8,
      modules: [
        { label: "Libro de presupuesto de cómputo", cost: 2, essential: true, why: "Mantiene comparables los experimentos y evita recomendar recursos inexistentes." },
        { label: "Banco de pilotos pequeños", cost: 2, essential: true, why: "Aporta mediciones reales con varios tamaños y cantidades de datos." },
        { label: "Ajustador de power laws", cost: 2, essential: true, why: "Resume la tendencia para estimar diseños todavía no entrenados." },
        { label: "Prueba de validación", cost: 1, essential: true, why: "Comprueba que la opción elegida mejora fuera de los datos usados para ajustar la tendencia." },
        { label: "Modelo máximo sin más datos", cost: 3, essential: false, why: "Gastar todo en parámetros puede dejar el modelo poco entrenado." },
        { label: "Detector de magia emergente", cost: 2, essential: false, why: "Una etiqueta vistosa no sustituye métricas continuas ni experimentos alrededor del supuesto umbral." },
      ],
    },
  },
  {
    levelId: "posttraining",
    role: "Entrenador de copilotos",
    outcome: "Convierte un modelo base en un ayudante que sigue instrucciones, mejora con preferencias y demuestra sus resultados.",
    bridge: "Escalar enseña patrones generales; después del pre-entrenamiento hacen falta ejemplos y señales que conviertan ese conocimiento en comportamiento útil.",
    concepts: [
      { concept: "SFT", plain: "Es ajustar el modelo con pares de instrucción y respuesta que muestran directamente el comportamiento deseado.", example: "El aprendiz ve «resume esta carta» junto a un resumen claro escrito o revisado por una persona." },
      { concept: "Preference optimization", plain: "Es entrenar con comparaciones que indican cuál de varias respuestas satisface mejor un criterio.", example: "Entre dos explicaciones, una evaluación marca la más clara y segura para orientar futuros ajustes." },
      { concept: "DPO", plain: "Es un método que acerca el modelo a respuestas preferidas y lo aleja de las rechazadas sin entrenar primero un reward model separado.", example: "Usa directamente una pareja ganadora y perdedora como señal para actualizar el asistente." },
      { concept: "RL", plain: "Es aprendizaje por refuerzo, donde una política cambia para obtener más recompensa de sus acciones o respuestas.", example: "El robot prueba una solución, recibe una puntuación y ajusta su estrategia para futuras rondas." },
      { concept: "GRPO", plain: "Es un método de optimización que compara la recompensa de varias respuestas del mismo grupo para calcular ventajas relativas.", example: "Genera cuatro intentos para un problema y aprende cuáles superan al promedio del grupo." },
      { concept: "Reward model", plain: "Es un modelo que convierte una respuesta y su contexto en una puntuación aprendida a partir de preferencias.", example: "Funciona como un juez entrenado con rankings, aunque su puntuación puede heredar errores de esos rankings." },
      { concept: "Verifier", plain: "Es un comprobador que evalúa si una respuesta o paso cumple criterios que pueden revisarse.", example: "Después de resolver una suma, vuelve a ejecutar las operaciones para confirmar el resultado." },
      { concept: "Distillation", plain: "Es transferir comportamientos de un modelo maestro a otro más pequeño mediante ejemplos o distribuciones producidas por el primero.", example: "Un copiloto grande crea demostraciones revisadas para enseñar a uno ligero que funcionará en el teléfono." },
    ],
    pipeline: {
      title: "Abre la academia del asistente",
      instruction: "Conecta una ruta de post-training que añade conducta útil y comprueba cada avance.",
      steps: [
        { label: "Enseñar con SFT", detail: "Usa demostraciones revisadas para que el modelo aprenda a interpretar y responder instrucciones." },
        { label: "Recoger comparaciones", detail: "Genera varias respuestas y registra preferencias o recompensas según criterios claros." },
        { label: "Optimizar la conducta", detail: "Aplica DPO, RL o GRPO con límites que eviten alejar el modelo sin control." },
        { label: "Verificar y transferir", detail: "Evalúa capacidades y seguridad; después puedes destilar el comportamiento validado a un modelo menor." },
      ],
    },
    sorter: {
      title: "Demostraciones y comparaciones",
      instruction: "Coloca cada pieza según enseñe una respuesta concreta o compare varias posibilidades.",
      lanes: [{ label: "Señal supervisada", description: "Muestra directamente qué salida debe imitar el modelo." }, { label: "Señal de preferencia o recompensa", description: "Distingue qué intento funciona mejor entre varias opciones." }],
      items: [
        { label: "Instrucción con respuesta ideal", lane: 0, why: "Es un ejemplo completo para SFT que el modelo intenta reproducir." },
        { label: "Demostración de herramienta correcta", lane: 0, why: "Muestra la llamada y el resultado esperados en una situación concreta." },
        { label: "Solución del maestro para destilar", lane: 0, why: "Proporciona una salida que el estudiante pequeño puede aprender a imitar." },
        { label: "Respuesta A preferida sobre B", lane: 1, why: "La pareja aporta una comparación directa para DPO u otra optimización de preferencias." },
        { label: "Puntuación de un reward model", lane: 1, why: "Resume una preferencia aprendida y puede alimentar un paso de RL." },
        { label: "Recompensas relativas de cuatro intentos", lane: 1, why: "GRPO usa la comparación dentro del grupo para orientar la actualización." },
      ],
    },
    build: {
      title: "Equipa la academia de post-training",
      brief: "Mejora seguimiento de instrucciones y razonamiento con señales revisables antes de pensar en comprimir el modelo.",
      budget: 9,
      modules: [
        { label: "Taller de ejemplos SFT", cost: 2, essential: true, why: "Establece el comportamiento inicial que debe mostrar el asistente." },
        { label: "Recolector de preferencias", cost: 2, essential: true, why: "Aporta comparaciones claras para mejorar más allá de la imitación." },
        { label: "Estación DPO o GRPO", cost: 2, essential: true, why: "Convierte las señales de preferencia o recompensa en actualizaciones del modelo." },
        { label: "Verifier y banco de evaluaciones", cost: 2, essential: true, why: "Comprueba que la mejora sea real y no rompa capacidades importantes." },
        { label: "Laboratorio reward model más RL", cost: 3, essential: false, why: "Ofrece otra ruta potente, pero una primera versión puede usar DPO sin juez separado." },
        { label: "Prensa de distillation", cost: 3, essential: false, why: "Reduce el modelo después de validar al maestro; no reemplaza las señales de entrenamiento." },
      ],
    },
  },
  {
    levelId: "align",
    role: "Director de conversación y guardián de la brújula",
    outcome: "Empaqueta un chat con sus roles y alinea sus respuestas con preferencias y límites revisables.",
    bridge: "El post-training ofrece las herramientas; ahora organizarás quién dice qué en el chat y orientarás la conducta del asistente con ellas.",
    concepts: [
      { concept: "Pre-entrenamiento", plain: "Es aprender patrones generales prediciendo texto en una colección enorme antes de practicar instrucciones concretas.", example: "El modelo completa millones de fragmentos y aprende lenguaje, pero todavía no sabe que debe responder como un asistente." },
      { concept: "Roles de chat", plain: "Son etiquetas que distinguen instrucciones del sistema, mensajes de la persona y respuestas del asistente dentro de una conversación.", example: "El rol system fija la regla del juego, user pide una receta y assistant ocupa el turno donde debe aparecer la respuesta." },
      { concept: "Chat template", plain: "Es la plantilla que convierte mensajes con roles en la secuencia exacta de tokens que el modelo aprendió a reconocer.", example: "Como un guion teatral, añade marcas de inicio, cambio de personaje y turno de respuesta sin mostrarlas como parte del diálogo." },
      { concept: "SFT (Supervised Fine-Tuning)", plain: "Es practicar con instrucciones y respuestas deseadas para dar forma inicial al comportamiento del asistente.", example: "Ve ejemplos donde una petición ambigua recibe una aclaración en vez de una suposición arriesgada." },
      { concept: "RLHF", plain: "Es usar preferencias humanas para entrenar una señal de recompensa y después mejorar el modelo mediante aprendizaje por refuerzo.", example: "Personas ordenan respuestas, un juez aprende esos rankings y el asistente practica para obtener mejores puntuaciones." },
      { concept: "Reward model", plain: "Es el juez aprendido que asigna una puntuación a una respuesta según comparaciones humanas anteriores.", example: "Puede premiar explicaciones claras, pero también aprender atajos si sus datos o criterios son pobres." },
      { concept: "PPO", plain: "Es un algoritmo de refuerzo que mejora la política con pasos limitados para no alejarla bruscamente de su versión de referencia.", example: "Como corregir el rumbo de un barco con giros pequeños en lugar de girar el timón por completo." },
      { concept: "DPO", plain: "Es una alternativa que aprende directamente de respuestas preferidas y rechazadas sin un reward model independiente.", example: "La pareja «esta ayuda / esta confunde» entra directamente al ajuste del modelo." },
      { concept: "Constitutional AI", plain: "Es un enfoque que usa principios escritos para criticar y revisar respuestas y producir nuevas señales de entrenamiento.", example: "El asistente compara un borrador con reglas de privacidad, explica el conflicto y redacta una versión más segura." },
    ],
    pipeline: {
      title: "Abre un chat y calibra su brújula",
      instruction: "Ordena el recorrido que lleva de mensajes con roles a una respuesta alineada y evaluada.",
      steps: [
        { label: "Etiquetar la conversación", detail: "Separa instrucciones de system, mensajes de user y turnos de assistant sin mezclar sus permisos." },
        { label: "Aplicar el chat template", detail: "Convierte los mensajes ordenados en la secuencia de tokens que espera el modelo pre-entrenado y afinado." },
        { label: "Dar forma con SFT", detail: "Practica conversaciones revisadas para establecer una primera política de asistente." },
        { label: "Preferir, optimizar y evaluar", detail: "Compara respuestas, usa DPO o reward model más PPO y comprueba utilidad, seguridad y separación correcta de roles." },
      ],
    },
    sorter: {
      title: "Guion del chat y brújula de conducta",
      instruction: "Separa las piezas que estructuran la conversación de las señales que indican qué respuesta se prefiere.",
      lanes: [{ label: "Estructura el chat", description: "Marca quién habla y cómo se empaquetan sus turnos para el modelo." }, { label: "Orienta la conducta", description: "Expresa qué respuesta o principio debe favorecer el entrenamiento." }],
      items: [
        { label: "Mensaje system con la regla", lane: 0, why: "El rol indica que esa pieza guía la conversación completa y no es una petición de usuario." },
        { label: "Mensaje user con la tarea", lane: 0, why: "La etiqueta conserva quién pidió la acción y evita presentarla como respuesta del modelo." },
        { label: "Marca de inicio del turno assistant", lane: 0, why: "El chat template señala el lugar exacto desde el que debe continuar el modelo." },
        { label: "Ranking humano entre A y B", lane: 1, why: "Registra cuál respuesta satisface mejor el criterio de la persona evaluadora." },
        { label: "Puntuación del reward model", lane: 1, why: "Aproxima preferencias anteriores para orientar un paso de RL, aunque no representa una verdad absoluta." },
        { label: "Crítica basada en una constitución", lane: 1, why: "Explica qué principio se incumple y orienta una revisión posterior." },
      ],
    },
    build: {
      title: "Monta una ruta de alineación revisable",
      brief: "Usa una ruta DPO sencilla para mejorar preferencias y demostrar que el cambio no sacrificó utilidad ni seguridad.",
      budget: 8,
      modules: [
        { label: "Roles y chat template", cost: 2, essential: true, why: "Entrega cada mensaje en la posición y con la etiqueta que el modelo espera." },
        { label: "Base con SFT conversacional", cost: 2, essential: true, why: "Proporciona una política inicial que ya practica instrucciones y respuestas por turnos." },
        { label: "Pares preferido y rechazado", cost: 2, essential: true, why: "Hacen explícita la dirección de comportamiento que se quiere reforzar." },
        { label: "DPO y evaluación de límites", cost: 2, essential: true, why: "Aprende de las parejas y comprueba que el cambio respete utilidad, seguridad y roles." },
        { label: "Reward model más PPO", cost: 3, essential: false, why: "Es una ruta RLHF alternativa, no una pieza adicional necesaria si ya elegiste DPO." },
        { label: "Constitución de revisión", cost: 1, essential: false, why: "Puede ampliar los criterios y generar críticas, aunque requiere evaluar sus propios puntos ciegos." },
      ],
    },
  },
  {
    levelId: "inference",
    role: "Controlador de tráfico de tokens",
    outcome: "Sirve respuestas rápidas a varias personas reutilizando memoria y manteniendo ocupado el hardware.",
    bridge: "El modelo ya aprendió y fue alineado; ahora debe responder con recursos limitados, poca espera y calidad comprobada.",
    concepts: [
      { concept: "Prefill", plain: "Es procesar todo el prompt en paralelo para crear las primeras representaciones y llenar el KV cache.", example: "Antes de hablar, el robot lee de una vez la pregunta y prepara fichas de memoria para cada posición." },
      { concept: "Decode", plain: "Es la fase que genera nuevos tokens uno por uno usando el contexto y la memoria ya preparados.", example: "Después de leer el pedido completo, entrega una palabra, actualiza su estado y calcula la siguiente." },
      { concept: "KV cache", plain: "Es la memoria de keys y values anteriores que evita recomputar toda la atención en cada token nuevo.", example: "Guarda las tarjetas ya clasificadas para que el siguiente paso solo añada la tarjeta reciente." },
      { concept: "Quantization", plain: "Es representar pesos o activaciones con menos bits para reducir memoria y, en hardware compatible, acelerar cálculos.", example: "Cambias cajas de dieciséis marcas por cajas de cuatro, pero pruebas que el redondeo no arruine respuestas importantes." },
      { concept: "Continuous batching", plain: "Es añadir y retirar solicitudes de un lote dinámico conforme llegan y terminan para no dejar huecos ociosos.", example: "Un autobús de tokens recoge un nuevo pasajero cuando otro baja sin esperar a que terminen todos los viajes." },
      { concept: "PagedAttention", plain: "Es administrar bloques del KV cache en páginas para usar memoria sin exigir espacios continuos enormes.", example: "Guarda capítulos en casilleros libres y conserva un índice, en vez de reservar una estantería completa para cada lector." },
      { concept: "Speculative decoding", plain: "Es dejar que un modelo pequeño proponga varios tokens y que el grande los verifique juntos sin cambiar el resultado aceptado.", example: "Un aprendiz adelanta tres fichas y el maestro confirma de una vez hasta dónde coincidió con su propia distribución." },
      { concept: "Serving", plain: "Es la capa que recibe solicitudes, programa cómputo, devuelve resultados y vigila latencia, capacidad y errores.", example: "Como un restaurante completo: no basta la cocina, también hacen falta fila, turnos, entrega y medidores." },
    ],
    pipeline: {
      title: "Despacha una respuesta en vivo",
      instruction: "Organiza el recorrido de una solicitud desde la cola hasta el último token entregado.",
      steps: [
        { label: "Admitir y agrupar", detail: "Valida la petición y el programador la coloca junto a otras solicitudes compatibles." },
        { label: "Ejecutar prefill", detail: "Procesa el prompt y reserva páginas para guardar sus keys y values." },
        { label: "Programar decode", detail: "Genera tokens por turnos con continuous batching y reutiliza el KV cache de cada solicitud." },
        { label: "Transmitir y medir", detail: "Envía tokens al usuario y registra latencia, uso de memoria, velocidad y errores." },
      ],
    },
    sorter: {
      title: "Andén de prefill y carril de decode",
      instruction: "Dirige cada trabajo a la fase donde ocurre principalmente durante una solicitud.",
      lanes: [{ label: "Prefill", description: "Procesa muchas posiciones conocidas del prompt y prepara su memoria." }, { label: "Decode", description: "Produce nuevas posiciones una a una y coordina solicitudes activas." }],
      items: [
        { label: "Leer 800 tokens del prompt", lane: 0, why: "Todas esas posiciones ya existen y pueden procesarse juntas al comienzo." },
        { label: "Crear keys y values iniciales", lane: 0, why: "El prompt llena el KV cache que se reutilizará durante la respuesta." },
        { label: "Reservar páginas de memoria", lane: 0, why: "El sistema prepara espacio para conservar el contexto de la solicitud." },
        { label: "Elegir el próximo token", lane: 1, why: "La respuesta autoregresiva avanza una nueva posición por paso." },
        { label: "Incorporar otra solicitud al lote", lane: 1, why: "Continuous batching reorganiza dinámicamente los trabajos que siguen generando." },
        { label: "Verificar propuestas del modelo draft", lane: 1, why: "Speculative decoding intenta aceptar varios tokens durante la fase de generación." },
      ],
    },
    build: {
      title: "Monta una estación de serving",
      brief: "Atiende varias conversaciones con memoria paginada y tiempos medibles antes de añadir aceleradores opcionales.",
      budget: 9,
      modules: [
        { label: "Cola y control de solicitudes", cost: 1, essential: true, why: "Recibe trabajo de forma ordenada y permite aplicar límites antes de usar el modelo." },
        { label: "Motor de prefill", cost: 2, essential: true, why: "Procesa el prompt y crea el estado inicial que necesita la generación." },
        { label: "KV cache paginado", cost: 2, essential: true, why: "Reutiliza atención anterior y administra memoria entre secuencias de longitudes distintas." },
        { label: "Scheduler de decode continuo", cost: 3, essential: true, why: "Mantiene solicitudes avanzando token a token sin esperar a que todo un lote termine." },
        { label: "Cuantizador de pesos", cost: 2, essential: false, why: "Puede ahorrar memoria si las evaluaciones confirman una pérdida de calidad aceptable." },
        { label: "Pareja draft y verificador", cost: 2, essential: false, why: "Puede acelerar el decode especulativo, pero el servicio básico funciona sin ella." },
      ],
    },
  },
];
