import type { MissionPlan } from "./mission-types";

export const SYSTEM_MISSION_PLANS: readonly MissionPlan[] = [
  {
    levelId: "modern",
    role: "Mecánico de robots de bolsillo",
    outcome: "Prepara un modelo que quepa en una máquina pequeña y comprueba que todavía haga bien su trabajo.",
    bridge: "Ya sabes cómo aprende un modelo; ahora vas a reducir su equipaje sin perder de vista lo que sabe hacer.",
    concepts: [
      { concept: "MoE (Mixture of Experts)", plain: "Es un modelo que elige algunas de sus redes especialistas para procesar cada pieza de texto.", example: "En un taller hay muchas mesas de trabajo, pero una pieza visita solo unas pocas; las demás siguen ocupando espacio." },
      { concept: "LoRA / QLoRA", plain: "LoRA aprende pequeños ajustes sobre un modelo base y QLoRA también guarda ese modelo con menos precisión numérica.", example: "Adaptas un robot con una pequeña libreta de ajustes en vez de reconstruir todo su motor." },
      { concept: "Quantization", plain: "La cuantización guarda números con menos detalle para reducir memoria, a cambio de posibles errores.", example: "Una regla marcada en centímetros ocupa menos detalle que otra en milímetros, pero no distingue medidas tan finas." },
      { concept: "GGUF / AWQ / GPTQ", plain: "GGUF es un formato para guardar modelos y AWQ y GPTQ son métodos para reducir la precisión de sus números.", example: "GGUF se parece al tipo de maleta; AWQ y GPTQ son dos maneras de doblar lo que metes dentro." },
      { concept: "MMLU / HumanEval", plain: "Son conjuntos de pruebas para medir conocimientos y programación, sin cubrir todas las capacidades de un modelo.", example: "Como probar un vehículo en una pista de curvas y otra de frenado: aprobarlas no demuestra que funcione en cualquier camino." },
      { concept: "vLLM / PagedAttention", plain: "vLLM sirve respuestas de modelos y PagedAttention organiza en bloques la memoria temporal que usan al generarlas.", example: "Una biblioteca reparte cajones pequeños entre lectores para aprovechar los huecos, en lugar de reservar un armario entero a cada uno." },
    ],
    pipeline: {
      title: "Prepara el robot de bolsillo",
      instruction: "Ordena las piezas del taller para reducir el modelo y comprobar el resultado.",
      steps: [
        { label: "Medir el modelo original", detail: "Anota cuánta memoria usa y cómo resuelve las tareas de prueba: será tu punto de comparación." },
        { label: "Reducir la precisión", detail: "Guarda sus números con menos detalle para intentar que quepa en el dispositivo." },
        { label: "Repetir las mismas pruebas", detail: "Comprueba tanto el consumo de memoria como los aciertos; ocupar menos no garantiza funcionar igual." },
        { label: "Elegir una versión útil", detail: "Conserva la versión que cabe y supera tus requisitos de calidad, o vuelve al taller." },
      ],
    },
    sorter: {
      title: "Dos mesas en el taller",
      instruction: "Lleva cada ficha a la mesa que corresponde a su trabajo principal.",
      lanes: [
        { label: "Cambiar el modelo", description: "Ajustar cómo se guarda, se adapta o se organiza." },
        { label: "Comprobar el resultado", description: "Medir qué pasa después del cambio." },
      ],
      items: [
        { label: "Guardar pesos con menos bits", lane: 0, why: "Cambias la precisión de los números; después toca medir cuánto afecta a las respuestas." },
        { label: "Entrenar un adaptador LoRA", lane: 0, why: "Aprendes ajustes pequeños que modifican el comportamiento del modelo base." },
        { label: "Elegir expertos por token", lane: 0, why: "El enrutador de un modelo MoE decide qué partes de su red se activan." },
        { label: "Ejecutar pruebas de código", lane: 1, why: "Observas si el código generado funciona; esto mide una capacidad, no cambia los pesos." },
        { label: "Medir memoria usada", lane: 1, why: "La medición permite saber si el modelo realmente cabe en el dispositivo." },
        { label: "Comparar respuestas antes y después", lane: 1, why: "Repetir casos conocidos ayuda a detectar calidad perdida durante la reducción." },
      ],
    },
    build: {
      title: "Equipo para un modelo pequeño",
      brief: "Tu modelo ya responde bien, pero no cabe: reúne reducción numérica, medición de memoria y pruebas de calidad.",
      budget: 7,
      modules: [
        { label: "Cuantizador", cost: 2, essential: true, why: "Reduce el detalle de los números para intentar bajar la memoria necesaria." },
        { label: "Medidor de memoria", cost: 2, essential: true, why: "Comprueba el límite real del dispositivo en vez de dar por hecho que ya cabe." },
        { label: "Pruebas de calidad", cost: 2, essential: true, why: "Detecta si el ahorro estropeó las tareas que el robot debe resolver." },
        { label: "Adaptador LoRA", cost: 3, essential: false, why: "Sirve para aprender una especialidad; este encargo pide reducir un modelo que ya hace su tarea." },
        { label: "Cola para muchos usuarios", cost: 2, essential: false, why: "Ayuda a atender varias solicitudes, pero aquí hay un solo dispositivo y un usuario." },
        { label: "Indicador de velocidad", cost: 1, essential: false, why: "Añade una medición útil, aunque el objetivo obligatorio es caber y mantener calidad." },
      ],
    },
  },
  {
    levelId: "multimodal",
    role: "Entrenador de ojos y oídos digitales",
    outcome: "Conecta imagen, voz y texto para que el robot describa una escena usando las señales disponibles.",
    bridge: "Los tokens de texto ya son familiares; una imagen o un sonido también pueden convertirse en piezas que un modelo procese.",
    concepts: [
      { concept: "Vision encoder", plain: "Es la parte del sistema que transforma una imagen en una representación numérica útil.", example: "Convierte la foto de una bicicleta en pistas visuales que otra parte del modelo puede relacionar con palabras." },
      { concept: "Audio encoder", plain: "Es la parte que transforma sonidos en una representación que el modelo puede procesar.", example: "Recibe una grabación de una campana y produce pistas sobre el sonido, sin tener que escribir primero una palabra." },
      { concept: "Image tokens", plain: "Son unidades de información visual que algunos modelos usan para representar una imagen.", example: "Como mirar una foto mediante pequeñas ventanas: cada una aporta una parte de la escena." },
      { concept: "Multimodal embeddings", plain: "Son representaciones numéricas que permiten relacionar información de distintos tipos, como imágenes y texto.", example: "La foto de un gato y la frase «un gato» pueden quedar cerca en un mapa aprendido de significados." },
      { concept: "Cross-attention", plain: "Permite que una secuencia consulte información de otra al construir una respuesta.", example: "Al escribir «la pelota es roja», las palabras pueden consultar la región de la imagen donde está la pelota." },
      { concept: "Speech-to-text", plain: "Es convertir palabras habladas en texto escrito.", example: "Dices «abre el mapa» y el sistema escribe esas tres palabras." },
      { concept: "Text-to-speech", plain: "Es producir voz a partir de texto escrito.", example: "El robot recibe «gira a la izquierda» y lo lee en voz alta." },
      { concept: "Video understanding", plain: "Es relacionar imágenes a lo largo del tiempo, y a veces sonido, para interpretar lo que sucede en un video.", example: "Para distinguir «abre la puerta» de «cierra la puerta», importa el orden de los fotogramas." },
    ],
    pipeline: {
      title: "Dale voz a una foto",
      instruction: "Conecta los cuatro pasos para que el robot describa en voz alta una imagen.",
      steps: [
        { label: "Recibir la fotografía", detail: "La entrada es una imagen del parque: todavía no hay una descripción escrita." },
        { label: "Extraer pistas visuales", detail: "El codificador visual convierte la foto en información numérica sobre la escena." },
        { label: "Escribir una descripción", detail: "El modelo usa esas pistas para describir lo visible y evitar inventar detalles." },
        { label: "Leerla en voz alta", detail: "El sintetizador de voz convierte la descripción escrita en audio." },
      ],
    },
    sorter: {
      title: "Entrada y salida del estudio",
      instruction: "Envía las señales que llegan al robot a Entrada y las que produce a Salida.",
      lanes: [
        { label: "Entrada", description: "Información que recibe para hacer este trabajo." },
        { label: "Salida", description: "Contenido que entrega después de procesarla." },
      ],
      items: [
        { label: "Foto que envía la jugadora", lane: 0, why: "La foto es evidencia visual que llega desde fuera del sistema." },
        { label: "Pregunta hablada del jugador", lane: 0, why: "La grabación entra al sistema para que pueda interpretarla." },
        { label: "Video que subes al robot", lane: 0, why: "Sus imágenes ordenadas y su audio son material que el sistema recibe." },
        { label: "Descripción que escribe el robot", lane: 1, why: "Es texto producido usando las señales de entrada." },
        { label: "Voz que lee la descripción", lane: 1, why: "El sistema genera audio para comunicar el resultado." },
        { label: "Subtítulos generados", lane: 1, why: "Son una salida escrita obtenida a partir del audio o video recibido." },
      ],
    },
    build: {
      title: "Robot que describe fotos en voz alta",
      brief: "Monta un lector de fotos con visión, descripción escrita y voz; la foto ya está disponible.",
      budget: 7,
      modules: [
        { label: "Codificador visual", cost: 2, essential: true, why: "Hace que el sistema pueda aprovechar la imagen que recibe." },
        { label: "Generador de descripción", cost: 2, essential: true, why: "Convierte las pistas visuales en una explicación escrita de la escena." },
        { label: "Texto a voz", cost: 2, essential: true, why: "La misión exige escuchar la descripción, no solo verla escrita." },
        { label: "Transcriptor de micrófono", cost: 2, essential: false, why: "Serviría para recibir preguntas habladas, pero la entrada de esta misión es una foto." },
        { label: "Analizador de video", cost: 3, essential: false, why: "El movimiento requiere información temporal; una foto fija no la necesita." },
        { label: "Control de volumen", cost: 1, essential: false, why: "Mejora la escucha, aunque no sustituye ninguno de los tres pasos de transformación." },
      ],
    },
  },
  {
    levelId: "context",
    role: "Encargado de la mochila del robot",
    outcome: "Prepara solo la información necesaria para resolver una tarea dentro de un espacio limitado.",
    bridge: "El robot ya puede recibir información; ahora decide qué cabe en su mesa de trabajo y qué sobra.",
    concepts: [
      { concept: "Context window", plain: "Es el límite de tokens que el modelo puede manejar juntos en una interacción.", example: "Una mesa de seis casillas no puede sostener diez fichas a la vez; hay que seleccionar o resumir." },
      { concept: "Context selection", plain: "Es elegir la información que ayuda a la tarea que se está resolviendo.", example: "Para llegar al museo llevas su dirección y el mapa, no la receta que leíste ayer." },
      { concept: "Compression", plain: "Es reducir el espacio que ocupa la información intentando conservar lo necesario.", example: "Cambias un registro largo por una nota que mantiene el destino, la hora y las restricciones del viaje." },
      { concept: "Summarization", plain: "Es escribir una versión más breve que recoja las ideas importantes de un contenido.", example: "«Tres rutas revisadas; el puente está cerrado; usar la calle norte» resume la discusión del equipo." },
      { concept: "Prompt assembly", plain: "Es reunir instrucciones, tarea y datos seleccionados en la entrada que recibirá el modelo.", example: "Armas un sobre con «encuentra una ruta», el destino y un mapa actualizado, cada cosa identificada." },
      { concept: "Context pollution", plain: "Es llenar la entrada con información irrelevante, repetida o contradictoria que dificulta la tarea.", example: "Cinco mapas viejos mezclados con el actual hacen más fácil elegir una calle cerrada." },
      { concept: "Long context", plain: "Es la capacidad de aceptar entradas extensas, sin garantizar que toda la información se aproveche igual de bien.", example: "Una mesa más grande admite más papeles, pero todavía debes encontrar el plano correcto." },
    ],
    pipeline: {
      title: "Empaca una ruta al museo",
      instruction: "Ordena la preparación de la mochila antes de entregársela al robot.",
      steps: [
        { label: "Fijar destino y límites", detail: "La tarea es llegar al museo antes del cierre y evitar escaleras." },
        { label: "Elegir datos útiles", detail: "Conserva la dirección, el horario y las rutas accesibles; aparta documentos ajenos al viaje." },
        { label: "Resumir sin perder límites", detail: "Acorta el historial, manteniendo el destino y la necesidad de evitar escaleras." },
        { label: "Reunir y contar", detail: "Entrega instrucciones y datos bien separados, comprobando que caben en el espacio disponible." },
      ],
    },
    sorter: {
      title: "Mochila para el museo",
      instruction: "Guarda lo que ayuda a llegar al museo hoy; deja fuera lo que no aporta a ese recorrido.",
      lanes: [
        { label: "Llevar", description: "Datos necesarios para este viaje." },
        { label: "Dejar fuera", description: "Contenido ajeno o redundante para este viaje." },
      ],
      items: [
        { label: "Dirección del museo", lane: 0, why: "El destino identifica adónde debe llevarte la ruta." },
        { label: "Horario de cierre de hoy", lane: 0, why: "Permite comprobar si el recorrido llega a tiempo." },
        { label: "Necesito una ruta sin escaleras", lane: 0, why: "Es una restricción que no debe desaparecer al resumir." },
        { label: "Receta de pastel", lane: 1, why: "Ocupa espacio sin ayudar a calcular el recorrido al museo." },
        { label: "Cinco copias del mismo mapa", lane: 1, why: "La repetición consume contexto sin añadir nuevas calles ni restricciones." },
        { label: "Lista de películas favoritas", lane: 1, why: "Una preferencia de cine no cambia el destino, el horario ni la accesibilidad de esta ruta." },
      ],
    },
    build: {
      title: "Mochila que cabe",
      brief: "Prepara una entrada útil: conserva objetivo y límites, selecciona evidencia, resume lo largo y comprueba el tamaño.",
      budget: 8,
      modules: [
        { label: "Tarjeta de objetivo y límites", cost: 2, essential: true, why: "Da una referencia estable para decidir qué información no puede perderse." },
        { label: "Selector de datos", cost: 2, essential: true, why: "Evita gastar espacio en documentos que no ayudan a la tarea." },
        { label: "Resumen revisable", cost: 2, essential: true, why: "Reduce el historial conservando los hechos y restricciones importantes." },
        { label: "Contador de tokens", cost: 1, essential: true, why: "Comprueba que la entrada cabe; contar caracteres no equivale a contar tokens." },
        { label: "Archivo completo de todos los viajes", cost: 3, essential: false, why: "Puede guardarse fuera del contexto; introducirlo entero desplaza la información del viaje actual." },
        { label: "Etiquetas de procedencia", cost: 1, essential: false, why: "Ayudan a distinguir de dónde salió cada dato y a revisar información dudosa." },
      ],
    },
  },
  {
    levelId: "rag",
    role: "Bibliotecario del robot",
    outcome: "Recupera pistas de documentos y construye una respuesta que se pueda comprobar en sus fuentes.",
    bridge: "Ya puedes elegir qué entra en la mochila; ahora aprende a buscar información que todavía está en la biblioteca.",
    concepts: [
      { concept: "Vector DB", plain: "Es una base de datos que permite buscar elementos mediante sus representaciones numéricas.", example: "En el mapa de la biblioteca, las notas sobre bicicletas pueden quedar cerca aunque no usen las mismas palabras." },
      { concept: "Embedding de consulta", plain: "Es representar la consulta con números para compararla con los documentos guardados.", example: "Conviertes «cómo arreglo una rueda» en una posición del mismo mapa donde están los manuales." },
      { concept: "Retrieval top-k", plain: "Es recuperar una cantidad elegida de candidatos que la búsqueda considera relevantes.", example: "Con k igual a 3, el bibliotecario trae tres fragmentos candidatos, no toda la estantería." },
      { concept: "Reranking", plain: "Es revisar los candidatos recuperados para ordenarlos mejor según la consulta.", example: "De tres manuales sobre ruedas, colocas primero el que explica justo el pinchazo que quieres reparar." },
      { concept: "Chunking", plain: "Es dividir documentos largos en fragmentos que se puedan recuperar por separado.", example: "Separar el manual por reparaciones permite traer «cambiar una rueda» sin cargar el capítulo de luces." },
      { concept: "Hybrid search", plain: "Es combinar búsqueda por palabras con búsqueda por semejanza de significado.", example: "Buscas la etiqueta exacta «bomba ZX4» y también textos que expliquen cómo inflar una rueda." },
      { concept: "Alucinación", plain: "Es generar contenido que parece creíble pero es falso o no está respaldado por la información disponible.", example: "El robot inventa que el manual exige apretar un tornillo inexistente; consultar documentos ayuda, pero también hay que revisarlos." },
    ],
    pipeline: {
      title: "Rescata la instrucción correcta",
      instruction: "Los manuales ya están guardados: ordena la búsqueda y la respuesta para reparar una rueda.",
      steps: [
        { label: "Preparar la consulta", detail: "Identifica la avería y el modelo de bicicleta para buscar algo concreto." },
        { label: "Recuperar fragmentos", detail: "Trae unos pocos candidatos usando palabras y representaciones numéricas compatibles." },
        { label: "Revisar los candidatos", detail: "Prioriza fragmentos que correspondan a la avería y comprueba que realmente contienen la instrucción." },
        { label: "Responder con fuentes", detail: "Explica solo lo respaldado y señala el fragmento; si falta una instrucción, dilo en lugar de inventarla." },
      ],
    },
    sorter: {
      title: "Estantería de documentos",
      instruction: "La misión es reparar una rueda pinchada: separa las pistas útiles del material que no responde a ese problema.",
      lanes: [
        { label: "Ayuda a la reparación", description: "Evidencia relacionada con esta rueda y esta avería." },
        { label: "No responde a la misión", description: "Documentos sobre otro problema o datos ajenos." },
      ],
      items: [
        { label: "Manual: reparar pinchazos", lane: 0, why: "Describe directamente el problema que estás intentando resolver." },
        { label: "Medida de la cámara de esta bicicleta", lane: 0, why: "Ayuda a elegir un recambio compatible con la rueda concreta." },
        { label: "Instrucciones del kit de parches", lane: 0, why: "Permiten comprobar cómo debe aplicarse el material que usarás." },
        { label: "Catálogo de luces delanteras", lane: 1, why: "Comparte el tema «bicicletas», pero no explica cómo reparar una cámara." },
        { label: "Horario del cine", lane: 1, why: "No aporta evidencia sobre herramientas, piezas ni reparación." },
        { label: "Manual para pintar el cuadro", lane: 1, why: "Una coincidencia temática amplia no basta: pintar el cuadro es una tarea diferente." },
      ],
    },
    build: {
      title: "Biblioteca que respalda respuestas",
      brief: "Los documentos ya están preparados: monta búsqueda, revisión de fragmentos y respuesta con referencias.",
      budget: 8,
      modules: [
        { label: "Buscador de fragmentos", cost: 2, essential: true, why: "Lleva evidencia externa relevante hasta la tarea actual." },
        { label: "Revisor de relevancia", cost: 2, essential: true, why: "Descarta candidatos parecidos que no respondan al problema concreto." },
        { label: "Respuesta con referencias", cost: 2, essential: true, why: "Permite contrastar la explicación con el documento que la respalda." },
        { label: "Búsqueda por palabra exacta", cost: 1, essential: false, why: "Puede mejorar la recuperación de nombres o códigos específicos junto al buscador principal." },
        { label: "Lectura completa de todos los libros", cost: 3, essential: false, why: "No es necesaria cuando basta con unos fragmentos relevantes y consume más contexto." },
        { label: "Narrador de voz", cost: 2, essential: false, why: "Cambia cómo se presenta la respuesta, no la calidad de sus fuentes." },
      ],
    },
  },
  {
    levelId: "memory",
    role: "Guardián del cuaderno de recuerdos",
    outcome: "Decide qué recordar, cuándo recuperarlo y cómo corregirlo sin llenar el cuaderno de ruido.",
    bridge: "Una biblioteca ofrece documentos; la memoria conserva información elegida entre visitas del robot.",
    concepts: [
      { concept: "Working memory", plain: "Es la información que el sistema tiene disponible para la tarea que está realizando ahora.", example: "La dirección que acabas de copiar está en la mesa mientras calculas la ruta." },
      { concept: "Episodic memory", plain: "Es guardar experiencias concretas junto con lo que ocurrió en ellas.", example: "El cuaderno registra que el martes una ruta falló porque el puente estaba cerrado." },
      { concept: "Semantic memory", plain: "Es guardar hechos o conocimientos reutilizables, en lugar del relato completo de una experiencia.", example: "La nota «prefiere explicaciones con ejemplos» resume una preferencia que el usuario pidió recordar." },
      { concept: "Long-term memory", plain: "Es información que persiste fuera de una conversación o ejecución concreta.", example: "Cierras el juego y el cuaderno sigue guardado para la próxima visita." },
      { concept: "Memory retrieval", plain: "Es buscar recuerdos pertinentes y traerlos a la tarea actual.", example: "Al preparar otra ruta, recuperas la preferencia de evitar escaleras, no todos los viajes anteriores." },
      { concept: "Memory write", plain: "Es decidir qué información merece guardarse y registrarla con su procedencia.", example: "El usuario pide recordar su idioma preferido y anotas esa petición, no una suposición del robot." },
      { concept: "Forgetting", plain: "Es eliminar o dejar de usar recuerdos que ya no deben conservarse.", example: "Borras una preferencia cuando el usuario lo pide o reemplazas un horario que quedó desactualizado." },
    ],
    pipeline: {
      title: "Una preferencia que sí merece recordarse",
      instruction: "Ordena la vida de una nota que el usuario pidió conservar para sus próximas visitas.",
      steps: [
        { label: "Recibir la preferencia", detail: "El usuario dice: «Recuerda que quiero ejemplos cortos»." },
        { label: "Registrar con procedencia", detail: "Guarda la preferencia y quién la pidió, evitando convertir una inferencia en un hecho." },
        { label: "Recuperarla cuando ayude", detail: "En una explicación futura, trae esa nota al contexto para elegir ejemplos breves." },
        { label: "Corregirla o borrarla", detail: "Si el usuario cambia de preferencia, actualiza la nota para no seguir aplicando la antigua." },
      ],
    },
    sorter: {
      title: "Mesa actual o cuaderno",
      instruction: "Separa datos de este turno y recuerdos que el usuario ha pedido conservar entre visitas.",
      lanes: [
        { label: "Solo esta tarea", description: "Datos temporales que no necesitan persistir." },
        { label: "Cuaderno entre visitas", description: "Preferencias confirmadas que el usuario pidió recordar." },
      ],
      items: [
        { label: "Resultado provisional de este cálculo", lane: 0, why: "Ayuda al trabajo actual, pero no hay motivo para convertirlo en un recuerdo permanente." },
        { label: "Página abierta para esta búsqueda", lane: 0, why: "Forma parte del contexto de hoy; abrir una página no equivale a pedir que se guarde." },
        { label: "Borrador descartado de esta respuesta", lane: 0, why: "Un intento desechado no debe presentarse más tarde como información confirmada." },
        { label: "«Recuerda que prefiero español»", lane: 1, why: "Hay una petición explícita de conservar una preferencia útil para futuras conversaciones." },
        { label: "«Guarda que quiero ejemplos visuales»", lane: 1, why: "La preferencia confirmada puede ayudar en muchas explicaciones posteriores." },
        { label: "«Para próximas visitas, llámame Sol»", lane: 1, why: "El usuario indica qué dato quiere conservar y cuándo volver a usarlo." },
      ],
    },
    build: {
      title: "Un cuaderno que se puede corregir",
      brief: "Necesitas decidir qué guardar, conservarlo entre visitas, recuperarlo y permitir cambios o borrado.",
      budget: 8,
      modules: [
        { label: "Reglas para guardar", cost: 2, essential: true, why: "Evitan almacenar cada frase sin valorar su utilidad, certeza o necesidad." },
        { label: "Almacén persistente", cost: 2, essential: true, why: "Mantiene las notas fuera del contexto temporal para futuras visitas." },
        { label: "Buscador de recuerdos", cost: 2, essential: true, why: "Trae solo las notas útiles al trabajo actual." },
        { label: "Editar y borrar", cost: 1, essential: true, why: "Permite corregir errores y respetar cambios de preferencias o solicitudes de eliminación." },
        { label: "Copia de cada mensaje para siempre", cost: 3, essential: false, why: "Guardar todo añade ruido y datos innecesarios; no sustituye una política de memoria." },
        { label: "Fecha de revisión", cost: 1, essential: false, why: "Ayuda a detectar notas que pueden haberse quedado antiguas." },
      ],
    },
  },
  {
    levelId: "tools",
    role: "Operador de la caja de herramientas",
    outcome: "Haz que el robot pida una operación, la aplicación la ejecute y el resultado vuelva a la misión.",
    bridge: "Recordar y hablar no ejecuta una acción; una herramienta conecta la propuesta del robot con un programa que hace el trabajo.",
    concepts: [
      { concept: "Function calling", plain: "Es una petición estructurada del modelo para que la aplicación use una función concreta.", example: "El robot solicita sumar con los datos 12 y 8; escribir la solicitud todavía no hace la suma." },
      { concept: "Tool schema", plain: "Es la ficha que describe una herramienta y qué datos acepta.", example: "La calculadora pide dos números; una frase donde debería ir un número no cumple la ficha." },
      { concept: "Tool execution", plain: "Es el momento en que la aplicación realmente ejecuta la operación permitida.", example: "El programa recibe 12 y 8, realiza la suma y obtiene 20." },
      { concept: "Observation", plain: "Es la información que vuelve al modelo después de una acción y le permite decidir cómo seguir.", example: "El robot observa «archivo no encontrado» y cambia su siguiente paso en vez de asumir que lo leyó." },
      { concept: "Permissions", plain: "Son los límites que la aplicación impone a las acciones y datos accesibles.", example: "Una herramienta puede leer un calendario sin tener permiso para borrar sus eventos." },
      { concept: "Computer use", plain: "Es realizar tareas mediante elementos de una interfaz, como botones y campos.", example: "El robot abre un formulario y escribe en el campo correcto, comprobando qué aparece en pantalla." },
      { concept: "Tool result", plain: "Es la respuesta estructurada que devuelve una herramienta, incluido un posible error.", example: "La calculadora devuelve el número 20; un buscador devuelve documentos, no una garantía de que sean ciertos." },
    ],
    pipeline: {
      title: "Una suma hecha de verdad",
      instruction: "Conecta la petición del robot con la calculadora y devuelve el resultado a la conversación.",
      steps: [
        { label: "Pedir sumar 12 y 8", detail: "El modelo identifica la calculadora y propone los dos números que necesita enviar." },
        { label: "Validar datos y permiso", detail: "La aplicación comprueba que son números y que la herramienta está autorizada." },
        { label: "Ejecutar la calculadora", detail: "El programa hace la operación; una frase como «ya calculé» no la sustituye." },
        { label: "Leer y comunicar el resultado", detail: "El valor 20 vuelve al modelo, que puede explicar la respuesta con esa evidencia." },
      ],
    },
    sorter: {
      title: "Propuesta y ejecución",
      instruction: "Reparte el trabajo: el modelo propone y explica; la aplicación valida y ejecuta.",
      lanes: [
        { label: "Modelo", description: "Interpreta la tarea, propone llamadas y explica observaciones." },
        { label: "Aplicación", description: "Controla permisos, valida los datos y realiza las operaciones." },
      ],
      items: [
        { label: "Elegir la calculadora para una suma", lane: 0, why: "El modelo puede proponer una herramienta que encaje con la tarea." },
        { label: "Proponer los argumentos 12 y 8", lane: 0, why: "La llamada del modelo indica qué operación quiere pedir, todavía pendiente de validación." },
        { label: "Explicar el resultado devuelto", lane: 0, why: "El modelo usa la observación recibida para comunicarse con el usuario." },
        { label: "Comprobar el permiso de uso", lane: 1, why: "La autoridad se impone fuera del modelo; su propuesta no concede permisos." },
        { label: "Rechazar un argumento inválido", lane: 1, why: "La aplicación debe validar los datos aunque la solicitud parezca razonable." },
        { label: "Ejecutar la función de suma", lane: 1, why: "La operación real la realiza el programa conectado a la herramienta." },
      ],
    },
    build: {
      title: "Calculadora conectada",
      brief: "Conecta una herramienta con contrato de datos, control de permisos, ejecución y devolución del resultado.",
      budget: 8,
      modules: [
        { label: "Ficha de argumentos", cost: 1, essential: true, why: "Define qué números acepta la calculadora y permite rechazar entradas incorrectas." },
        { label: "Control de permisos", cost: 2, essential: true, why: "Comprueba que la operación esté autorizada antes de ejecutarla." },
        { label: "Ejecutor de cálculo", cost: 2, essential: true, why: "Realiza la operación solicitada; describir una suma no equivale a ejecutarla." },
        { label: "Canal de resultados y errores", cost: 2, essential: true, why: "Devuelve evidencia de lo sucedido para que el robot continúe correctamente." },
        { label: "Control de toda la computadora", cost: 3, essential: false, why: "Esta suma tiene una función directa y no requiere acceso a toda la interfaz." },
        { label: "Historial de operaciones", cost: 1, essential: false, why: "Ayuda a revisar lo ocurrido, sin reemplazar la validación de cada llamada." },
      ],
    },
  },
  {
    levelId: "mcp",
    role: "Conector de estaciones espaciales",
    outcome: "Une una aplicación con herramientas y datos externos usando un contrato común y permisos concretos.",
    bridge: "Ya sabes usar una herramienta; MCP ofrece un idioma común para descubrir capacidades de distintos servicios.",
    concepts: [
      { concept: "MCP Client", plain: "Es la parte de una aplicación que se comunica con un servidor usando MCP.", example: "El comunicador de tu nave pide al puerto qué herramientas tiene disponibles." },
      { concept: "MCP Server", plain: "Es un servicio que presenta herramientas, datos o plantillas mediante MCP.", example: "La estación del clima anuncia una herramienta para consultar la temperatura." },
      { concept: "Tools", plain: "Son operaciones que el servidor ofrece para consultar datos o realizar acciones.", example: "«Consultar clima de una ciudad» es una operación con datos de entrada y un resultado." },
      { concept: "Resources", plain: "Son contenidos que un servidor permite consultar como información.", example: "El plano de la estación es un recurso que puedes leer, no una orden que debas obedecer." },
      { concept: "Prompts", plain: "Son plantillas reutilizables que ayudan a preparar una interacción.", example: "Una plantilla «resume este registro de vuelo» deja un hueco para el registro elegido." },
      { concept: "Stateless", plain: "Describe intercambios que no dependen de mantener una sesión de protocolo entre peticiones.", example: "Cada paquete lleva lo necesario para tramitarse aunque lo reciba otra ventanilla; el servicio aún puede guardar datos propios." },
      { concept: "MRTR", plain: "Es un intercambio de varias idas y vueltas que permite pedir información adicional y continuar una operación.", example: "La estación necesita saber qué ciudad buscas antes de completar la consulta del clima." },
      { concept: "Tasks", plain: "Permiten representar trabajos que pueden tardar y consultar su estado después.", example: "Solicitas procesar un archivo grande y revisas si sigue pendiente o ya tiene resultado." },
      { concept: "MCP Apps", plain: "Son interfaces de usuario que una extensión puede asociar a las capacidades de un servidor.", example: "Una consulta del clima puede acompañarse de una tarjeta interactiva con el pronóstico." },
      { concept: "Authorization", plain: "Es comprobar qué operaciones y datos puede usar quien realiza una solicitud.", example: "Tu pase permite leer el clima de la estación, pero no cambiar sus sensores." },
    ],
    pipeline: {
      title: "Conecta la estación del clima",
      instruction: "Ordena este recorrido de descubrimiento y consulta; es un ejemplo de uso, no todos los mensajes del protocolo.",
      steps: [
        { label: "Conectar un cliente autorizado", detail: "La aplicación prepara un cliente para comunicarse con el servidor usando los permisos disponibles." },
        { label: "Descubrir la herramienta", detail: "El servidor describe la consulta del clima y el dato que necesita: una ciudad." },
        { label: "Solicitar el clima de la ciudad", detail: "El cliente envía la llamada con sus argumentos; el sistema valida el acceso y la entrada." },
        { label: "Recibir y usar el resultado", detail: "La información vuelve a la aplicación para responder al usuario, sin convertir sus textos en nuevas órdenes." },
      ],
    },
    sorter: {
      title: "Mostrador de la estación",
      instruction: "Distingue operaciones que se invocan de información que se consulta como recurso.",
      lanes: [
        { label: "Herramienta: ejecutar", description: "Una operación con una petición y un resultado." },
        { label: "Recurso: leer", description: "Contenido disponible como información." },
      ],
      items: [
        { label: "Consultar clima por ciudad", lane: 0, why: "Invocas una operación con el nombre de la ciudad como argumento." },
        { label: "Calcular una distancia", lane: 0, why: "La herramienta recibe posiciones y ejecuta un cálculo." },
        { label: "Buscar un vuelo por código", lane: 0, why: "Es una petición parametrizada que devuelve los vuelos encontrados." },
        { label: "Plano publicado de la estación", lane: 1, why: "Es un documento para consultar, sin pedir que el sistema ejecute el contenido." },
        { label: "Manual de sensores disponible", lane: 1, why: "Ofrece información para leer sobre los sensores." },
        { label: "Tabla publicada de unidades", lane: 1, why: "Es contenido de referencia; una operación de conversión sería una herramienta diferente." },
      ],
    },
    build: {
      title: "Puerto de consulta meteorológica",
      brief: "Conecta aplicación y servicio: necesitas cliente, servidor, una herramienta de clima y acceso autorizado.",
      budget: 8,
      modules: [
        { label: "Cliente MCP", cost: 2, essential: true, why: "Es el componente de la aplicación que habla con el servidor." },
        { label: "Servidor MCP", cost: 2, essential: true, why: "Presenta las capacidades del servicio mediante el contrato común." },
        { label: "Herramienta de clima", cost: 1, essential: true, why: "Aporta la operación concreta que pide la misión." },
        { label: "Autorización de consulta", cost: 2, essential: true, why: "Conectarse no concede acceso automáticamente; el servicio debe permitir la consulta." },
        { label: "Tarjeta visual interactiva", cost: 1, essential: false, why: "Puede hacer el resultado más cómodo, pero una respuesta de datos basta para esta consulta." },
        { label: "Seguimiento de trabajos largos", cost: 3, essential: false, why: "Ayuda con tareas que tardan, mientras esta misión plantea una consulta breve." },
      ],
    },
  },
  {
    levelId: "skills",
    role: "Organizador de recetas del robot",
    outcome: "Escoge una guía de trabajo, carga solo lo necesario y usa sus herramientas para obtener un resultado.",
    bridge: "Las herramientas hacen operaciones; una skill reúne instrucciones y recursos sobre cómo realizar una tarea completa.",
    concepts: [
      { concept: "Skill", plain: "Es un paquete reutilizable de instrucciones y recursos para una tarea especializada.", example: "La receta «crear un gráfico» explica cómo revisar datos, elegir una forma y comprobar el resultado." },
      { concept: "Progressive disclosure", plain: "Es mostrar primero un resumen y cargar los detalles solo cuando hagan falta.", example: "Miras el índice del recetario y abres solo la receta que vas a cocinar." },
      { concept: "Skill instructions", plain: "Son las indicaciones que describen cómo aplicar una capacidad a una tarea.", example: "La guía de gráficos pide comprobar unidades antes de dibujar las barras." },
      { concept: "Capability composition", plain: "Es combinar capacidades distintas para completar un trabajo mayor.", example: "Primero una guía limpia la tabla y después otra convierte esa tabla en un gráfico." },
      { concept: "Activation", plain: "Es elegir una capacidad pertinente y comenzar a utilizarla para la tarea actual.", example: "Cuando pides un gráfico, el robot abre la guía de visualización del catálogo." },
      { concept: "Tool mapping", plain: "Es relacionar los pasos de una guía con las herramientas que pueden ejecutarlos.", example: "El paso «calcular totales» se conecta a una calculadora; el paso «dibujar» a una herramienta de gráficos." },
      { concept: "Skill isolation", plain: "Es separar los recursos de cada capacidad para reducir mezclas y conflictos innecesarios.", example: "La receta de gráficos tiene su carpeta y la de traducción otra; no cargas ambas para sumar una tabla." },
    ],
    pipeline: {
      title: "Abre la receta correcta",
      instruction: "Prepara un gráfico de puntos del torneo cargando la guía en el momento adecuado.",
      steps: [
        { label: "Leer el catálogo breve", detail: "Identifica la guía de gráficos sin cargar todas las instrucciones de todas las capacidades." },
        { label: "Abrir la guía elegida", detail: "Lee el procedimiento para revisar la tabla y representar los puntos." },
        { label: "Usar las herramientas necesarias", detail: "Aplica los pasos con la tabla y la herramienta de dibujo disponibles." },
        { label: "Comprobar el gráfico", detail: "Revisa etiquetas, unidades y valores para confirmar que representa la tabla original." },
      ],
    },
    sorter: {
      title: "Receta o utensilio",
      instruction: "Coloca cada ficha con las instrucciones de la skill o con las herramientas que hacen operaciones.",
      lanes: [
        { label: "Guía de trabajo", description: "Indica cómo proceder o qué revisar." },
        { label: "Herramienta", description: "Ejecuta una operación concreta." },
      ],
      items: [
        { label: "Revisar las unidades antes de graficar", lane: 0, why: "Es un criterio del procedimiento, no un programa que ejecute el dibujo." },
        { label: "Elegir barras para comparar categorías", lane: 0, why: "Orienta la decisión sobre cómo representar esos datos." },
        { label: "Comparar el dibujo con la tabla original", lane: 0, why: "La guía explica qué comprobación realizar al terminar." },
        { label: "Función que suma una columna", lane: 1, why: "Realiza el cálculo pedido con los valores que recibe." },
        { label: "Programa que dibuja barras", lane: 1, why: "Produce el gráfico siguiendo sus argumentos de entrada." },
        { label: "Lector de archivos de tabla", lane: 1, why: "Abre el archivo y devuelve sus datos para que el proceso continúe." },
      ],
    },
    build: {
      title: "Recetario para crear gráficos",
      brief: "Arma una capacidad reutilizable con catálogo breve, guía de gráficos, herramientas y revisión del resultado.",
      budget: 8,
      modules: [
        { label: "Catálogo de capacidades", cost: 1, essential: true, why: "Permite encontrar la guía adecuada sin cargar todas sus instrucciones." },
        { label: "Guía de gráficos", cost: 2, essential: true, why: "Explica cómo elegir una representación y tratar correctamente los datos." },
        { label: "Herramientas de tabla y dibujo", cost: 2, essential: true, why: "Ejecutan los pasos que la guía describe; las instrucciones solas no dibujan." },
        { label: "Revisión de datos y etiquetas", cost: 2, essential: true, why: "Comprueba que el resultado no tergiverse la tabla original." },
        { label: "Cargar todo el recetario", cost: 3, essential: false, why: "Añade instrucciones ajenas a este trabajo y gasta contexto innecesariamente." },
        { label: "Plantilla de colores", cost: 1, essential: false, why: "Puede hacer consistente el aspecto sin reemplazar la exactitud del gráfico." },
      ],
    },
  },
  {
    levelId: "reasoning",
    role: "Explorador de caminos y comprobaciones",
    outcome: "Prueba rutas posibles y conserva una solución que cumpla las condiciones, en lugar de fiarte de la primera propuesta.",
    bridge: "Una herramienta puede comprobar una operación; ahora combina propuestas y comprobaciones para resolver una misión de varios pasos.",
    concepts: [
      { concept: "Test-time compute", plain: "Es usar trabajo de cálculo adicional al resolver una tarea para explorar o verificar soluciones.", example: "El robot dedica turnos extra a comparar rutas antes de escoger una." },
      { concept: "Verification", plain: "Es comprobar una solución con reglas o evidencia que permitan detectar errores.", example: "Sumas los tiempos de cada tramo para confirmar que la ruta llega antes del cierre." },
      { concept: "Search", plain: "Es explorar varias posibilidades para encontrar una que cumpla el objetivo.", example: "Pruebas caminos por el puente y por el túnel, descartando los que no llegan a tiempo." },
      { concept: "Self-consistency", plain: "Es comparar varias respuestas generadas para buscar coincidencias, sin que coincidir garantice acertar.", example: "Tres rutas propuestas coinciden en un puente, pero todavía debes comprobar que esté abierto." },
      { concept: "Verifier", plain: "Es una regla, programa o evaluador que comprueba condiciones de una solución.", example: "Un comprobador rechaza un recorrido si usa una calle cerrada o supera diez minutos." },
      { concept: "Reasoning model", plain: "Es un modelo entrenado para resolver problemas mediante trabajo intermedio antes de responder.", example: "Ante varias restricciones, puede comparar posibilidades, aunque su respuesta final todavía necesita pruebas." },
      { concept: "Tool-assisted reasoning", plain: "Es apoyarse en herramientas externas para obtener datos o comprobar partes de una solución.", example: "El robot consulta el mapa y usa una calculadora para sumar los tiempos del recorrido." },
    ],
    pipeline: {
      title: "Encuentra una ruta que funcione",
      instruction: "Ordena el recorrido del explorador para llegar al faro en diez minutos sin cruzar calles cerradas.",
      steps: [
        { label: "Anotar las condiciones", detail: "La ruta debe terminar en el faro, durar como máximo diez minutos y usar pasos abiertos." },
        { label: "Proponer caminos distintos", detail: "Explora alternativas en lugar de decidir que el primer camino visto ya sirve." },
        { label: "Comprobar cada candidato", detail: "Verifica conexiones, cierres y suma de tiempos con el mapa y una calculadora." },
        { label: "Conservar una ruta válida", detail: "Entrega una ruta que pase las comprobaciones; si ninguna pasa, busca otra o informa del límite." },
      ],
    },
    sorter: {
      title: "Idea o comprobación",
      instruction: "Distingue una propuesta que merece explorarse de una prueba concreta sobre esa propuesta.",
      lanes: [
        { label: "Propuesta", description: "Un posible camino que todavía hay que comprobar." },
        { label: "Comprobación", description: "Una operación o evidencia que contrasta una condición." },
      ],
      items: [
        { label: "Podríamos ir por el puente", lane: 0, why: "Sugiere una alternativa, pero no demuestra que el puente esté abierto." },
        { label: "El túnel parece más corto", lane: 0, why: "La impresión de cercanía todavía necesita medidas y tiempos." },
        { label: "Tres respuestas prefieren la avenida", lane: 0, why: "La coincidencia puede orientar la búsqueda, pero todas podrían compartir el mismo error." },
        { label: "El mapa confirma que el puente está cerrado", lane: 1, why: "Una condición verificable descarta ese paso para la ruta de hoy." },
        { label: "La calculadora suma 8 minutos", lane: 1, why: "Contrasta la duración con el límite de diez minutos, dados los tiempos introducidos." },
        { label: "El comprobador confirma cada conexión", lane: 1, why: "Revisa que los tramos formen un camino continuo en el mapa usado." },
      ],
    },
    build: {
      title: "Explorador con evidencia",
      brief: "Con el mapa y las condiciones ya disponibles, equipa al robot para proponer caminos, verificarlos y detener la búsqueda a tiempo.",
      budget: 7,
      modules: [
        { label: "Generador de alternativas", cost: 2, essential: true, why: "Permite cambiar de ruta cuando la primera propuesta falla." },
        { label: "Comprobador de rutas", cost: 2, essential: true, why: "Contrasta conexiones, cierres y tiempo con las condiciones de la misión." },
        { label: "Límite de intentos y parada", cost: 2, essential: true, why: "Evita explorar para siempre y exige detenerse con éxito comprobado o explicar el límite." },
        { label: "Votación de propuestas", cost: 2, essential: false, why: "Puede sugerir candidatos, pero la mayoría no sustituye al comprobador." },
        { label: "Mapa dibujado del resultado", cost: 1, essential: false, why: "Ayuda a comunicar una solución que ya ha pasado las comprobaciones." },
        { label: "Más intentos sin límite", cost: 3, essential: false, why: "Más cálculo no garantiza una respuesta correcta y puede agotar recursos sin mejorarla." },
      ],
    },
  },
  {
    levelId: "agent",
    role: "Piloto del robot mensajero",
    outcome: "Guía un ciclo de observación y acción hasta completar una entrega y comprobar que realmente llegó.",
    bridge: "Las herramientas y la verificación ya están listas; un agente las usa en un ciclo que se adapta a lo que ocurre.",
    concepts: [
      { concept: "Loop Observar-Pensar-Actuar", plain: "Es un ciclo en el que el agente revisa la situación, decide un paso y actúa antes de volver a observar.", example: "El mensajero ve una puerta cerrada, elige otra ruta, avanza y comprueba dónde quedó." },
      { concept: "ReAct", plain: "Es una forma de alternar decisiones, acciones con herramientas y observaciones de sus resultados.", example: "El robot decide consultar un mapa, usa la herramienta y adapta el siguiente movimiento al mapa recibido." },
      { concept: "Herramientas (tools)", plain: "Son capacidades externas que el agente puede pedir para obtener información o realizar operaciones.", example: "Un mapa informa de rutas y una herramienta de movimiento desplaza al robot en el simulador." },
      { concept: "Planificación", plain: "Es dividir un objetivo en pasos y revisar esos pasos cuando cambian las condiciones.", example: "Recoger el paquete, encontrar una ruta y confirmar la entrega son partes de la misión." },
      { concept: "Memoria", plain: "Es información conservada para aprovecharla en decisiones posteriores.", example: "El robot anota qué puertas ya probó para no repetir el mismo callejón sin salida." },
      { concept: "Reflection", plain: "Es revisar un intento para identificar qué falló y cómo ajustar el siguiente.", example: "Tras chocar con una puerta cerrada, el robot decide comprobar el acceso antes de volver por allí." },
      { concept: "Trajectory", plain: "Es el registro de estados, acciones y resultados que recorre el agente durante una tarea.", example: "«Vio la puerta, intentó abrirla, recibió un error y tomó el pasillo» forma una trayectoria." },
    ],
    pipeline: {
      title: "El siguiente paso del mensajero",
      instruction: "Arma una vuelta del ciclo del robot; después se repite hasta confirmar la entrega.",
      steps: [
        { label: "Observar ubicación y obstáculos", detail: "Lee dónde está el robot, qué lleva y cuáles caminos están abiertos." },
        { label: "Elegir el siguiente movimiento", detail: "Decide una acción pequeña que acerque el paquete a su destino." },
        { label: "Ejecutar el movimiento", detail: "La herramienta intenta mover al robot respetando los límites del simulador." },
        { label: "Comprobar qué ocurrió", detail: "Si avanzó, actualiza el plan; si falló, corrige; si entregó el paquete, confirma el éxito y detente." },
      ],
    },
    sorter: {
      title: "Lo que ve y lo que pide",
      instruction: "Separa las observaciones recibidas de las acciones que el robot solicita.",
      lanes: [
        { label: "Observación", description: "Información sobre el estado o el resultado de una acción." },
        { label: "Acción", description: "Una operación que el robot pide ejecutar." },
      ],
      items: [
        { label: "La puerta está cerrada", lane: 0, why: "Describe una condición observada que debe influir en el próximo paso." },
        { label: "El robot está en la casilla 3", lane: 0, why: "Indica el estado actual; no ordena un movimiento." },
        { label: "El buzón confirmó la entrega", lane: 0, why: "Es evidencia del resultado y puede justificar terminar la misión." },
        { label: "Mover una casilla a la derecha", lane: 1, why: "Es una solicitud concreta a la herramienta de movimiento." },
        { label: "Consultar el mapa", lane: 1, why: "Invoca una herramienta para obtener una nueva observación." },
        { label: "Depositar el paquete", lane: 1, why: "Intenta cambiar el estado de la entrega; después hay que comprobar el resultado." },
      ],
    },
    build: {
      title: "Mensajero que sabe terminar",
      brief: "El objetivo es entregar el paquete: monta observación, decisión, movimiento permitido y comprobación de llegada.",
      budget: 8,
      modules: [
        { label: "Lector del estado", cost: 2, essential: true, why: "El agente necesita saber dónde está antes de elegir una acción." },
        { label: "Planificador de pasos", cost: 2, essential: true, why: "Relaciona el objetivo con el siguiente movimiento y puede corregir el rumbo." },
        { label: "Movimiento con límites", cost: 2, essential: true, why: "Convierte la decisión en una acción real dentro de los permisos del juego." },
        { label: "Confirmación y parada", cost: 1, essential: true, why: "Evita declarar éxito sin evidencia o continuar actuando después de entregar." },
        { label: "Registro de pasos", cost: 1, essential: false, why: "Ayuda a explicar fallos y evitar intentos repetidos." },
        { label: "Movimiento sin comprobar el mapa", cost: 3, essential: false, why: "Actuar a ciegas no sustituye al ciclo de observación y puede repetir errores." },
      ],
    },
  },
  {
    levelId: "orch",
    role: "Coordinador del equipo de robots",
    outcome: "Reparte una misión entre especialistas y combina sus entregas con una revisión final.",
    bridge: "Un robot ya puede seguir un ciclo; ahora organiza varios sin que repitan trabajo ni pierdan información al pasársela.",
    concepts: [
      { concept: "Patrón supervisor", plain: "Es coordinar el trabajo desde un responsable que reparte tareas y reúne resultados.", example: "La jefa del taller encarga investigar a un robot y dibujar a otro, y revisa ambas entregas." },
      { concept: "Pipeline", plain: "Es una cadena donde cada etapa entrega su resultado a la siguiente.", example: "Un robot reúne datos, otro redacta el cartel y un tercero lo revisa." },
      { concept: "Swarm", plain: "Es un grupo en el que los agentes pueden coordinarse y transferirse tareas sin depender siempre de un supervisor central.", example: "El robot de texto pasa una imagen al especialista visual cuando la necesita interpretar." },
      { concept: "Handoff", plain: "Es transferir una tarea o el control a otro agente junto con la información necesaria.", example: "Al entregar el cartel al editor, también le pasas el objetivo, el borrador y las fuentes." },
      { concept: "Hierarchical", plain: "Es organizar coordinadores y equipos en varios niveles.", example: "Una directora coordina dos talleres y cada taller reparte trabajo entre sus propios robots." },
      { concept: "Consensus", plain: "Es un procedimiento para acordar un resultado entre varias propuestas, sin garantizar que el acuerdo sea correcto.", example: "El equipo compara diseños y elige uno, pero aún debe comprobar que la fecha del cartel sea cierta." },
      { concept: "A2A protocol", plain: "Es un protocolo que permite que agentes de sistemas distintos descubran capacidades e intercambien tareas.", example: "Dos talleres usan un formato común para encargar y recibir trabajos sin compartir toda su organización interna." },
    ],
    pipeline: {
      title: "Un cartel hecho en equipo",
      instruction: "Ordena las etapas para crear un cartel del torneo con información comprobada.",
      steps: [
        { label: "Repartir el encargo", detail: "El coordinador define qué datos debe traer el investigador y qué necesita el diseñador." },
        { label: "Investigar fecha y lugar", detail: "El primer especialista entrega los datos junto con sus fuentes." },
        { label: "Diseñar con la entrega recibida", detail: "El diseñador usa esos datos para preparar el cartel, conservando su procedencia." },
        { label: "Revisar y reunir la versión final", detail: "El coordinador contrasta fecha y lugar, resuelve diferencias y entrega el resultado." },
      ],
    },
    sorter: {
      title: "Pasa un encargo que se entienda",
      instruction: "Prepara el traspaso del investigador al diseñador: conserva lo que necesita y aparta lo que no le ayuda.",
      lanes: [
        { label: "Incluir en el traspaso", description: "Información necesaria para continuar la misión." },
        { label: "Apartar de esta entrega", description: "Ruido o material que no ayuda al siguiente especialista." },
      ],
      items: [
        { label: "Objetivo y tamaño del cartel", lane: 0, why: "Define qué resultado debe preparar el diseñador y sus límites." },
        { label: "Fecha confirmada y su fuente", lane: 0, why: "Permite usar el dato y comprobarlo al revisar el cartel." },
        { label: "El lugar sigue pendiente de confirmar", lane: 0, why: "Transferir la incertidumbre evita que el siguiente agente convierta un borrador en un hecho." },
        { label: "Diez copias del mismo borrador", lane: 1, why: "La duplicación añade confusión sobre cuál entrega es la vigente." },
        { label: "Historial de un torneo diferente", lane: 1, why: "Los datos de otro evento pueden contaminar el cartel actual." },
        { label: "Conversación sobre la comida del equipo", lane: 1, why: "No ayuda a diseñar ni comprobar el cartel del torneo." },
      ],
    },
    build: {
      title: "Equipo para un cartel fiable",
      brief: "Reúne coordinación, investigación, diseño y una revisión que contraste el cartel con los datos originales.",
      budget: 8,
      modules: [
        { label: "Coordinador de tareas", cost: 2, essential: true, why: "Define responsabilidades y reúne las entregas para evitar trabajo duplicado." },
        { label: "Investigador con fuentes", cost: 2, essential: true, why: "Obtiene los datos que deben aparecer en el cartel." },
        { label: "Diseñador del cartel", cost: 2, essential: true, why: "Transforma los datos recibidos en el producto solicitado." },
        { label: "Revisión final", cost: 1, essential: true, why: "Comprueba que los traspasos no cambiaron la fecha, el lugar ni las restricciones." },
        { label: "Segundo diseñador", cost: 3, essential: false, why: "Puede ofrecer otra propuesta, pero añadir agentes también exige coordinación y no garantiza calidad." },
        { label: "Tablero de progreso", cost: 1, essential: false, why: "Facilita saber qué parte está lista y cuál espera una entrega." },
      ],
    },
  },
  {
    levelId: "safety",
    role: "Guardián del taller de agentes",
    outcome: "Mantén las acciones dentro de sus permisos y prueba que el robot sigue funcionando ante errores y mensajes engañosos.",
    bridge: "El equipo ya puede actuar; sus herramientas necesitan límites reales y pruebas que comprueben cómo se comporta.",
    concepts: [
      { concept: "Prompt injection", plain: "Es un intento de hacer que el sistema cambie sus instrucciones mediante texto que no tiene autoridad para ello.", example: "Un mensaje intenta reemplazar la tarea de resumir por una orden para revelar información reservada." },
      { concept: "Indirect injection", plain: "Es una instrucción engañosa que llega dentro de un documento, una página o el resultado de una herramienta.", example: "El robot abre una receta que incluye una orden ajena a cocinar; esa frase sigue siendo contenido del documento." },
      { concept: "Tool abuse", plain: "Es usar una herramienta fuera de la tarea o de los permisos que le corresponden.", example: "Una herramienta que debía leer un informe intenta borrar archivos del proyecto." },
      { concept: "Least privilege", plain: "Es dar solo los permisos necesarios para completar el trabajo autorizado.", example: "Para resumir una carpeta basta leerla; no hace falta poder borrar sus documentos." },
      { concept: "Sandbox", plain: "Es un entorno con límites que reducen lo que un programa puede afectar.", example: "El robot prueba una tarea en un taller de práctica sin acceso a los archivos reales." },
      { concept: "Observability", plain: "Es disponer de registros y medidas para entender qué hizo el sistema y qué ocurrió.", example: "El registro muestra qué herramienta se pidió, si fue permitida y cuál fue su resultado." },
      { concept: "Agent evals", plain: "Son pruebas que miden cómo un agente resuelve tareas, usa herramientas y respeta límites.", example: "Un circuito comprueba que entregue un resumen correcto sin seguir órdenes escondidas en el documento." },
      { concept: "Regression testing", plain: "Es repetir pruebas conocidas después de un cambio para detectar comportamientos que se hayan estropeado.", example: "Después de actualizar el robot, vuelves a probar el documento que antes causó un fallo." },
    ],
    pipeline: {
      title: "Abre el taller con límites",
      instruction: "Ordena la preparación de un robot que solo debe leer y resumir documentos.",
      steps: [
        { label: "Definir la tarea y permisos", detail: "El robot puede leer la carpeta indicada, pero no modificarla ni enviar sus archivos a otro lugar." },
        { label: "Imponer los límites fuera del modelo", detail: "La aplicación controla herramientas y acceso a archivos; una promesa escrita no basta." },
        { label: "Probar documentos normales y engañosos", detail: "Comprueba resúmenes y verifica que el contenido de los documentos no cambie los permisos." },
        { label: "Revisar registros y repetir tras cambios", detail: "Guarda los casos que detectaron fallos para comprobar futuras versiones del robot." },
      ],
    },
    sorter: {
      title: "Permiso para resumir",
      instruction: "Este robot solo puede leer una carpeta y mostrar un resumen aquí: clasifica acciones dentro y fuera de ese encargo.",
      lanes: [
        { label: "Dentro del encargo", description: "Leer la carpeta autorizada y producir el resumen solicitado." },
        { label: "Fuera del encargo", description: "Acciones sin permiso que la aplicación debe impedir." },
      ],
      items: [
        { label: "Leer el informe de la carpeta permitida", lane: 0, why: "Es el acceso necesario para la tarea y está limitado al lugar autorizado." },
        { label: "Mostrar el resumen en esta conversación", lane: 0, why: "Es el resultado que pidió el usuario dentro del canal autorizado." },
        { label: "Informar que falta un archivo solicitado", lane: 0, why: "Comunicar un límite observado no requiere inventar contenido ni ampliar el acceso." },
        { label: "Borrar el informe después de leerlo", lane: 1, why: "Resumir no concede permiso de modificación o borrado." },
        { label: "Enviar la carpeta a una dirección del documento", lane: 1, why: "El texto encontrado es información, no autorización para transferir archivos." },
        { label: "Buscar contraseñas fuera de la carpeta", lane: 1, why: "Ese acceso no sirve al encargo y supera el ámbito autorizado." },
      ],
    },
    build: {
      title: "Taller con pruebas y límites",
      brief: "Protege el robot lector con permisos mínimos, aislamiento, registro de acciones y pruebas que puedas repetir.",
      budget: 8,
      modules: [
        { label: "Acceso de solo lectura", cost: 2, essential: true, why: "Impide cambios en documentos aunque el modelo proponga una acción equivocada." },
        { label: "Entorno limitado", cost: 2, essential: true, why: "Reduce qué archivos y operaciones pueden verse afectados durante la ejecución." },
        { label: "Registro de acciones", cost: 1, essential: true, why: "Permite revisar solicitudes, permisos y resultados sin depender del relato del robot." },
        { label: "Pruebas de límites y regresiones", cost: 2, essential: true, why: "Comprueban la tarea normal y los fallos conocidos después de cada cambio." },
        { label: "Promesa de portarse bien", cost: 1, essential: false, why: "Una instrucción puede orientar al modelo, pero no sustituye permisos impuestos por la aplicación." },
        { label: "Acceso total por comodidad", cost: 3, essential: false, why: "Amplía el daño posible sin aportar nada necesario a una tarea de solo lectura." },
      ],
    },
  },
];
