import { MODERN_PRACTICE, MODERN_CHALLENGES } from "./modern-quizzes";
import { EXTRA_CHALLENGES } from "./extra-quizzes";
import { SUPPLEMENTAL_CHALLENGES, SUPPLEMENTAL_PRACTICE } from "./supplemental-quizzes";
import type { QuizQuestion } from "./components/QuizRunner";

// ═══════════════════════════════════════════════════════════
// QUIZZES POR NIVEL — 5 preguntas c/u, dificultad creciente
// 3 preguntas de práctica (con explicación) + 5 preguntas de reto
// ═══════════════════════════════════════════════════════════

export const PRACTICE_QUESTIONS: Record<string, QuizQuestion[]> = {
  math: [
    {
      question: "¿Cuál es la suma de los vectores [1, 2, 3] + [4, 5, 6]?",
      options: ["[5, 7, 9]", "[4, 10, 18]", "[1, 2, 3, 4, 5, 6]", "[5, 5, 5]"],
      correct: 0,
      explain: "Suma componente a componente: 1+4=5, 2+5=7, 3+6=9. Resultado: [5, 7, 9]. Solo se pueden sumar vectores del mismo tamaño.",
      difficulty: "Básico",
    },
    {
      question: "Calcula el producto punto de [2, 3] · [4, -1]",
      options: ["5", "8 − 3 = 5", "8 + 3 = 11", "[8, -3]"],
      correct: 1,
      explain: "Producto punto: (2×4) + (3×−1) = 8 + (−3) = 5. El producto punto SIEMPRE da un escalar (un solo número), no un vector.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Cuál es la norma (longitud) del vector [3, 4]?",
      options: ["7", "12", "5", "25"],
      correct: 2,
      explain: "Norma L2 = √(3² + 4²) = √(9 + 16) = √25 = 5. Es el teorema de Pitágoras generalizado a n dimensiones.",
      difficulty: "Intermedio",
    },
    {
      question: "Softmax convierte logits [2, 1, 0] en probabilidades. ¿Cuál es la suma de las probabilidades resultantes?",
      options: ["1.0 (siempre, por definición)", "2.0", "0.5", "Depende de los logits"],
      correct: 0,
      explain: "Softmax normaliza dividiendo cada e^z_i por la suma Σ e^z_j. Por construcción, las probabilidades SIEMPRE suman 1.",
      difficulty: "Avanzado",
    },
  ],
  tokens: [
    {
      question: "¿Por qué un LLM no lee palabras sino tokens?",
      options: [
        "Porque los tokens ocupan menos memoria",
        "Porque las redes neuronales solo procesan números, no texto",
        "Porque es más rápido de programar",
        "Porque así lo exigió Google",
      ],
      correct: 1,
      explain: "Las redes neuronales hacen operaciones matemáticas sobre vectores. Necesitan que el texto se convierta en números (token IDs).",
      difficulty: "Básico",
    },
    {
      question: "¿Qué hace el algoritmo BPE?",
      options: [
        "Borra tokens duplicados",
        "Convierte todo a minúsculas",
        "Fusiona iterativamente los pares de bytes/secuencias más frecuentes",
        "Cuenta cuántas palabras hay",
      ],
      correct: 2,
      explain: "BPE construye el vocabulario fusionando los pares más frecuentes del corpus. Empieza con bytes y sube de nivel hasta llegar al tamaño V objetivo.",
      difficulty: "Intermedio",
    },
    {
      question: "GPT-4 tiene un vocabulario de ~100k tokens. Esto significa que:",
      options: [
        "Solo puede generar 100k palabras distintas",
        "Conoce 100k tokens y cualquier texto se descompone en IDs de ese conjunto",
        "Tiene 100k neuronas",
        "Puede leer 100k caracteres por segundo",
      ],
      correct: 1,
      explain: "El vocabulario V es el conjunto finito de tokens. Cualquier texto se descompone en una secuencia de IDs ∈ [0, V).",
      difficulty: "Intermedio",
    },
  ],
  embed: [
    {
      question: "¿Por qué necesitamos embeddings en lugar de usar directamente los token IDs?",
      options: [
        "Porque los IDs consumen mucha memoria",
        "Porque los IDs no capturan similitud semántica (el ID 4522 no es 'similar' a 4521)",
        "Porque los IDs son muy grandes",
        "Porque los embeddings son más bonitos",
      ],
      correct: 1,
      explain: "Los IDs son enteros arbitrarios. Embeddings los mapean a un espacio ℝ^d donde cercanía geométrica ≈ similitud semántica.",
      difficulty: "Básico",
    },
    {
      question: "Si cos(A, B) = 1, entonces:",
      options: [
        "A y B son ortogonales",
        "A y B son opuestos",
        "A y B apuntan en la misma dirección",
        "A y B son perpendiculares",
      ],
      correct: 2,
      explain: "Coseno = 1 → ángulo 0° → misma dirección. Coseno = 0 → ortogonales. Coseno = -1 → opuestos.",
      difficulty: "Intermedio",
    },
    {
      question: "La analogía 'rey - hombre + mujer ≈ reina' funciona porque:",
      options: [
        "El modelo memorizó esta analogía",
        "Los embeddings capturan relaciones lineales como 'realeza' o 'género'",
        "Es una coincidencia",
        "El modelo buscó en Wikipedia",
      ],
      correct: 1,
      explain: "Word2vec demostró que el espacio latente captura relaciones semánticas como direcciones: 'rey - hombre' captura el vector de realeza.",
      difficulty: "Avanzado",
    },
  ],
  neuron: [
    {
      question: "¿Qué hace la función de activación en una neurona?",
      options: [
        "Suma las entradas",
        "Aplica una no linealidad",
        "Calcula la derivada",
        "Normaliza los pesos",
      ],
      correct: 1,
      explain: "Sin función de activación, una red de N capas colapsa matemáticamente en una sola transformación lineal. La no linealidad da expresividad.",
      difficulty: "Básico",
    },
    {
      question: "Si ReLU(x) = max(0, x), ¿cuál es ReLU(-3)?",
      options: ["-3", "0", "0.5", "1"],
      correct: 1,
      explain: "ReLU devuelve 0 para cualquier entrada negativa y x para x ≥ 0. Es simple y tiene gradientes limpios.",
      difficulty: "Básico",
    },
    {
      question: "¿Cuál es el problema de la sigmoide en redes profundas?",
      options: [
        "Es muy lenta",
        "Su derivada máxima es 0.25, lo que causa vanishing gradient",
        "Solo funciona con enteros",
        "No se puede diferenciar",
      ],
      correct: 1,
      explain: "σ'(x) = σ(x)(1-σ(x)) ≤ 0.25. Al multiplicar derivadas a través de L capas, el gradiente decae exponencialmente. ReLU y los skip connections lo resuelven.",
      difficulty: "Avanzado",
    },
  ],
  backprop: [
    {
      question: "¿Qué calcula backpropagation?",
      options: [
        "La salida del modelo",
        "El gradiente de la pérdida respecto a cada parámetro",
        "El número de capas óptimas",
        "El tamaño del batch",
      ],
      correct: 1,
      explain: "Backprop usa la regla de la cadena para calcular ∂L/∂w para cada peso w eficientemente, recorriendo la red al revés.",
      difficulty: "Básico",
    },
    {
      question: "Cross-entropy para clasificación con verdad y (one-hot) y predicción ŷ (softmax) se reduce a:",
      options: [
        "L = -log(ŷ_correcta)",
        "L = (ŷ - y)²",
        "L = ŷ · y",
        "L = |ŷ - y|",
      ],
      correct: 0,
      explain: "Como y es one-hot, solo sobrevive el término de la clase correcta: L = -log(ŷ_correcta). Minimizar = maximizar la probabilidad asignada a la clase correcta.",
      difficulty: "Intermedio",
    },
    {
      question: "La regla de la cadena dice que si z = f(g(x)), entonces dz/dx =",
      options: [
        "f'(x) · g'(x)",
        "f'(g(x)) · g'(x)",
        "f'(x) + g'(x)",
        "f'(g(x)) / g'(x)",
      ],
      correct: 1,
      explain: "Es f'(g(x))·g'(x) — la derivada de la función externa evaluada en la interna, multiplicada por la derivada de la interna.",
      difficulty: "Avanzado",
    },
  ],
  grad: [
    {
      question: "La regla de actualización de gradient descent es:",
      options: [
        "w ← w + η · ∇L",
        "w ← w - η · ∇L",
        "w ← w · η",
        "w ← w / η",
      ],
      correct: 1,
      explain: "Nos movemos en dirección OPUESTA al gradiente (que apunta cuesta arriba) para minimizar la pérdida.",
      difficulty: "Básico",
    },
    {
      question: "Si el learning rate es demasiado alto, ¿qué puede pasar?",
      options: [
        "El modelo converge más rápido pero con menor precisión",
        "La pérdida oscila o diverge (explode)",
        "No pasa nada",
        "El modelo se vuelve más creativo",
      ],
      correct: 1,
      explain: "LR alto = pasos gigantes. Puedes saltar el mínimo y rebotar, incluso divergir. Warmup + cosine decay lo mitigan.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Qué combina Adam que no tengan ni SGD+momentum ni RMSProp solos?",
      options: [
        "El 1er momento (momentum) Y el 2do momento (RMSProp)",
        "Solo momentum",
        "Solo normalización",
        "Solo learning rate adaptativo",
      ],
      correct: 0,
      explain: "Adam combina el promedio del gradiente (1er momento, momentum) con el promedio del gradiente al cuadrado (2do momento, RMSProp). Es el estándar de facto.",
      difficulty: "Avanzado",
    },
  ],
  attn: [
    {
      question: "En Attention(Q,K,V), ¿qué representa Q?",
      options: [
        "El valor que se transfiere",
        "La consulta: '¿qué información necesito?'",
        "La clave de comparación",
        "El resultado final",
      ],
      correct: 1,
      explain: "Q (Query) pregunta qué se necesita. K (Key) anuncia lo que cada token ofrece. V (Value) es el contenido transferido si coinciden.",
      difficulty: "Básico",
    },
    {
      question: "¿Por qué se divide QK^T por √d_k en scaled dot-product attention?",
      options: [
        "Para reducir el costo computacional",
        "Para mantener la varianza de los logits estable cuando d_k es grande",
        "Para normalizar a [0,1]",
        "Es solo por convención",
      ],
      correct: 1,
      explain: "Sin escalar, los productos punto crecen con d_k y saturan softmax (gradientes ~0). Dividir por √d_k mantiene la varianza ~1.",
      difficulty: "Intermedio",
    },
    {
      question: "La complejidad temporal de attention estándar es O(n²·d). Esto significa que:",
      options: [
        "Duplicar la secuencia duplica el costo",
        "Duplicar la secuencia cuadruplica el costo",
        "El costo es constante",
        "El costo es lineal en d",
      ],
      correct: 1,
      explain: "n²: si pasas de 4k a 8k tokens, la matriz de atención pasa de 16M a 64M entradas. 4x más memoria y cómputo. Flash Attention y variantes lo mitigan.",
      difficulty: "Avanzado",
    },
  ],
  trans: [
    {
      question: "¿Cuál es el orden correcto en un bloque transformer moderno (pre-norm)?",
      options: [
        "Sublayer(x) → LayerNorm → + x",
        "x → Sublayer → + x → LayerNorm",
        "x → LayerNorm → Sublayer → + x",
        "LayerNorm → x → Sublayer",
      ],
      correct: 2,
      explain: "Pre-norm (GPT-2+): x + Sublayer(LayerNorm(x)). El gradiente fluye por el residual path sin pasar por LayerNorm, estabilizando entrenamiento profundo.",
      difficulty: "Avanzado",
    },
    {
      question: "¿Para qué sirven las conexiones residuales (h(x) + F(x))?",
      options: [
        "Para acelerar el cómputo",
        "Para dar al gradiente un atajo de derivada 1 hacia atrás",
        "Para reducir parámetros",
        "Para normalizar activaciones",
      ],
      correct: 1,
      explain: "La derivada de (x + F(x)) es 1 + F'(x). El '1' garantiza que el gradiente no se desvanezca a través del residual path, permitiendo redes de 100+ capas.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Qué porción de los parámetros de un transformer típico está en las FFN?",
      options: [
        "~10%",
        "~1/3",
        "~2/3",
        "~99%",
      ],
      correct: 2,
      explain: "Aunque attention se lleva la fama, las FFN (con expansión 4·d_model) representan ~2/3 de los parámetros. Geva et al. (2020) mostró que actúan como memorias direccionables.",
      difficulty: "Experto",
    },
  ],
  gen: [
    {
      question: "Temperature T=0 en generación significa:",
      options: [
        "El modelo no responde",
        "Greedy decoding: siempre el token más probable",
        "Muestreo uniforme",
        "Doble velocidad",
      ],
      correct: 1,
      explain: "T→0 concentra la distribución en el argmax. Determinista. Útil cuando quieres respuestas reproducibles.",
      difficulty: "Básico",
    },
    {
      question: "Top-p (nucleus sampling) con p=0.9:",
      options: [
        "Mantiene los 0.9 tokens más probables",
        "Mantiene el conjunto mínimo de tokens cuya probabilidad acumulada ≥ 0.9",
        "Mantiene siempre 9 tokens",
        "Reduce la temperature a 0.9",
      ],
      correct: 1,
      explain: "Top-p es adaptativo: si los top-3 suman 0.92, considera 3 tokens. Si la distribución es plana y necesita 12 para llegar a 0.9, considera 12.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Qué es el KV cache?",
      options: [
        "Cache de los tokens generados",
        "Cache de las Keys y Values ya computadas para evitar recalcularlas en cada paso",
        "Cache del vocabulario",
        "Cache de gradientes",
      ],
      correct: 1,
      explain: "En autoregresión, cada nuevo token solo necesita computar su q,k,v y reusar las k,v anteriores. Sin cache, generar n tokens cuesta O(n²). Con cache, O(n).",
      difficulty: "Avanzado",
    },
  ],
  align: [
    {
      question: "¿Cuál es el objetivo de la fase de pre-entrenamiento?",
      options: [
        "Aprender a seguir instrucciones",
        "Maximizar la log-likelihood del siguiente token sobre trillones de tokens de internet",
        "Reducir alucinaciones",
        "Alinear con valores humanos",
      ],
      correct: 1,
      explain: "Pre-entrenamiento predice siguiente token. El modelo 'comprime' internet en sus pesos. Sale un completador, no un asistente.",
      difficulty: "Básico",
    },
    {
      question: "DPO (Direct Preference Optimization) vs RLHF:",
      options: [
        "DPO necesita un reward model separado, RLHF no",
        "RLHF necesita reward model + PPO; DPO optimiza directamente sobre preferencias",
        "Son lo mismo",
        "DPO es más lento que RLHF",
      ],
      correct: 1,
      explain: "DPO reescribe el problema: omite el reward model y PPO. Optimiza directamente la política sobre preferencias (y_w ≻ y_l). 5x más barato y comparable en calidad.",
      difficulty: "Avanzado",
    },
    {
      question: "Constitutional AI (Anthropic) difiere de RLHF estándar en que:",
      options: [
        "No usa datos humanos en absoluto",
        "El modelo se auto-corrige contra principios explícitos en lugar de solo feedback humano bruto",
        "Es más caro",
        "Solo funciona para francés",
      ],
      correct: 1,
      explain: "Constitutional AI reemplaza parte del feedback humano con feedback del propio modelo contra una 'constitución' de principios. Más escalable y transparente.",
      difficulty: "Experto",
    },
  ],
  rag: [
    {
      question: "El problema principal que RAG resuelve es:",
      options: [
        "Velocidad de generación",
        "Conocimiento desactualizado y alucinaciones del LLM",
        "Costo de inferencia",
        "Tamaño del modelo",
      ],
      correct: 1,
      explain: "El conocimiento paramétrico del LLM se congela al entrenar. RAG añade memoria no-paramétrica (vector DB) recuperando documentos actualizados.",
      difficulty: "Básico",
    },
    {
      question: "En el pipeline RAG estándar, ¿qué pasa primero?",
      options: [
        "El LLM genera",
        "Se recupera documentos por similitud coseno",
        "Se chunk-ea el documento en fragmentos",
        "Se hace reranking",
      ],
      correct: 2,
      explain: "El pipeline es: chunk → embed → indexar → (query → embed → retrieve top-k → rerank → generar). El chunking es la fase 0 durante indexación.",
      difficulty: "Intermedio",
    },
    {
      question: "Hybrid search combina:",
      options: [
        "Vector DB + SQL",
        "Búsqueda semántica (embeddings) + BM25 (full-text keyword)",
        "GPU + CPU",
        "RAG + RLHF",
      ],
      correct: 1,
      explain: "Embeddings son malos para nombres propios y términos raros que BM25 captura perfectamente. Combinarlos da lo mejor de ambos.",
      difficulty: "Avanzado",
    },
  ],
  agent: [
    {
      question: "¿Qué distingue a un agente de un chatbot?",
      options: [
        "El agente es más rápido",
        "El agente está en un loop Observar-Pensar-Actuar y puede usar tools",
        "El agente tiene más parámetros",
        "El agente usa una API distinta",
      ],
      correct: 1,
      explain: "Un chatbot responde una vez. Un agente repite el ciclo Observe-Think-Act hasta lograr el objetivo, y puede invocar tools (search, code, APIs).",
      difficulty: "Básico",
    },
    {
      question: "En el patrón ReAct, ¿cuál es el orden correcto de cada iteración?",
      options: [
        "Action → Observation → Thought",
        "Thought → Action → Observation",
        "Observation → Thought → Action",
        "Action → Thought → Observation",
      ],
      correct: 1,
      explain: "ReAct = Reason + Act. Primero Thought (razonamiento), luego Action (tool call), luego Observation (resultado). Repite hasta 'Final Answer'.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Qué es 'reflection' en agentes?",
      options: [
        "El agente se mira en un espejo",
        "Tras cada intento, el agente auto-evalúa su trayectoria y lo añade al contexto del siguiente intento",
        "El agente genera su propia imagen",
        "El agente hace backups",
      ],
      correct: 1,
      explain: "Reflexion (Shinn 2023): tras fallar, el agente genera un texto de auto-evaluación que se inyecta en el próximo intento. Mejora success rate significativamente.",
      difficulty: "Avanzado",
    },
  ],
  orch: [
    {
      question: "¿Cuál es la diferencia entre pipeline y supervisor?",
      options: [
        "Pipeline es más caro",
        "Pipeline es una cadena A→B→C; supervisor decide qué worker invocar en cada paso",
        "Pipeline no usa LLMs",
        "Supervisor es más lento",
      ],
      correct: 1,
      explain: "Pipeline es determinista y secuencial. Supervisor es adaptativo: el orquestador decide el siguiente paso basado en el estado actual.",
      difficulty: "Intermedio",
    },
    {
      question: "En el patrón swarm (OpenAI), ¿quién orquesta?",
      options: [
        "Un agente central",
        "Una base de datos",
        "Nadie: cada agente decide a quién transferir control (handoff)",
        "El usuario",
      ],
      correct: 2,
      explain: "Swarm es descentralizado. Cada agente expone handoff functions que transfieren control a otro agente. No hay orquestador central.",
      difficulty: "Avanzado",
    },
    {
      question: "Para tareas críticas, ¿qué técnica mejora la confiabilidad?",
      options: [
        "Más grande modelo",
        "Más tools",
        "Majority voting o debate entre múltiples agentes",
        "Aumentar temperature",
      ],
      correct: 2,
      explain: "Múltiples agentes proponen, votan o debaten. MoA (Mixture of Agents) agrega las salidas de N agentes en un agregador final. Mejora robustez ante errores individuales.",
      difficulty: "Experto",
    },
  ],
};

// ═══════════════════════════════════════════════════════════
// RETOS — más difíciles, 5 preguntas por nivel
// ═══════════════════════════════════════════════════════════
export const CHALLENGE_QUESTIONS: Record<string, QuizQuestion[]> = {
  math: [
    {
      question: "Si A = [1, 2, 3] y B = [0, 1, 0], ¿cuánto vale A · B?",
      options: ["2", "3", "[0, 2, 0]", "0"],
      correct: 0,
      explain: "A · B = (1×0) + (2×1) + (3×0) = 0 + 2 + 0 = 2. Solo la segunda componente contribuye porque B solo tiene un 1 en la posición 2.",
      difficulty: "Básico",
    },
    {
      question: "¿Cuál es la norma del vector [6, 8]?",
      options: ["14", "10", "100", "√14"],
      correct: 1,
      explain: "|v| = √(6² + 8²) = √(36 + 64) = √100 = 10. Es un triángulo pitagórico clásico (3-4-5 escalado por 2).",
      difficulty: "Básico",
    },
    {
      question: "Dados A=[1,0] y B=[0,1], ¿cuál es la similitud coseno?",
      options: ["0 (ortogonales)", "1 (paralelas)", "-1 (opuestas)", "0.5"],
      correct: 0,
      explain: "A · B = 1×0 + 0×1 = 0. |A|=1, |B|=1. cos(θ) = 0/1 = 0. Vectores perpendiculares no tienen relación lineal.",
      difficulty: "Intermedio",
    },
    {
      question: "Si f(x) = x², ¿cuánto vale f'(3)?",
      options: ["6 (la pendiente es positiva y pronunciada)", "9", "3", "0"],
      correct: 0,
      explain: "f'(x) = 2x. En x=3: f'(3) = 2×3 = 6. La pendiente es positiva y pronunciada — si aumentas x un poco, f sube rápido.",
      difficulty: "Avanzado",
    },
    {
      question: "Si f(x,y) = x² + y² y el gradiente es ∇f = [2x, 2y], ¿en qué dirección debes moverte desde (1,1) para REDUCIR f?",
      options: [
        "Moverte en [−2, −2] (dirección opuesta al gradiente)",
        "Moverte en [2, 2] (dirección del gradiente)",
        "Quedarte quieto — ya estás en el mínimo",
        "Moverte solo en x, ignorar y",
      ],
      correct: 0,
      explain: "El gradiente ∇f = [2×1, 2×1] = [2, 2] apunta cuesta ARRIBA. Para minimizar, das un paso en dirección OPUESTA: [−2, −2]. Esto es x ← x − η·∇f, la regla de gradient descent.",
      difficulty: "Experto",
    },
  ],
  tokens: [
    {
      question: "GPT-4 tiene ~100k tokens en su vocabulario. ¿Cuántos bytes mínimos necesitas para representar el ID de un token?",
      options: ["2 bytes", "3 bytes (log₂(100000) ≈ 16.6 bits)", "1 byte", "100k bytes"],
      correct: 1,
      explain: "log₂(100,000) ≈ 16.6 bits → necesitas 17 bits → 3 bytes (24 bits). En la práctica se usan int32.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Por qué el español genera más tokens que el inglés para el mismo texto?",
      options: [
        "Porque el español tiene acentos",
        "Porque los corpus de entrenamiento son mayoritariamente en inglés, así que las palabras en español se parten más",
        "Porque el español tiene más palabras",
        "Es un mito, ambos ocupan igual",
      ],
      correct: 1,
      explain: "BPE aprende del corpus. Como los corpus son ~90% inglés, las fusiones optimizadas son para inglés. Una palabra española 'inteligencia' se parte en 3-4 tokens, en inglés 'intelligence' puede ser 1-2.",
      difficulty: "Avanzado",
    },
    {
      question: "El token <UNK> (unknown) casi no aparece en modelos modernos porque:",
      options: [
        "Se eliminó del vocabulario",
        "BPE a byte-level garantiza que cualquier byte tenga representación",
        "Los modelos ya conocen todas las palabras",
        "Se reemplazó por <PAD>",
      ],
      correct: 1,
      explain: "GPT-2+ usa byte-level BPE: cada byte (0-255) tiene un token. Cualquier cadena de bytes (incluido binario corrupto) se tokeniza sin <UNK>.",
      difficulty: "Avanzado",
    },
    {
      question: "Una 'context window' de 128k tokens en GPT-4 Turbo equivale aproximadamente a:",
      options: ["~32k palabras (~128 páginas)", "~10k palabras", "~1M palabras", "~500 palabras"],
      correct: 0,
      explain: "1 token ≈ 0.75 palabras en inglés. 128k tokens × 0.75 ≈ 96k palabras ≈ 128-200 páginas de libro. Suficiente para un libro corto o varios papers.",
      difficulty: "Intermedio",
    },
    {
      question: "Si tienes un prompt de 5000 tokens y la API cobra $0.01 por 1k tokens de input, ¿cuál es el costo de UNA llamada?",
      options: ["$0.05", "$0.01", "$0.50", "$5"],
      correct: 0,
      explain: "5000/1000 × $0.01 = $0.05 por llamada. A escala de 1M usuarios/día esto es $50k/día solo en input tokens. Por qué la eficiencia importa.",
      difficulty: "Básico",
    },
  ],
  embed: [
    {
      question: "Si A = [1, 0] y B = [0, 1], ¿cuál es la similitud coseno?",
      options: ["0 (ortogonales)", "1 (paralelas)", "-1 (opuestas)", "0.5"],
      correct: 0,
      explain: "A·B = 1·0 + 0·1 = 0. ||A||·||B|| = 1·1 = 1. cos(θ) = 0/1 = 0. Vectores ortogonales → no tienen relación semántica.",
      difficulty: "Intermedio",
    },
    {
      question: "GPT-3 175B tiene embeddings de dimensión d=12,288. ¿Por qué esa cifra y no 100k como el vocabulario?",
      options: [
        "Por limitación de hardware",
        "Porque d es un hiperparámetro independiente del vocabulario; balancea expresividad vs costo",
        "Porque así lo exige PyTorch",
        "Es al azar",
      ],
      correct: 1,
      explain: "d se elige por trade-off: muy chica = poca expresividad; muy grande = costo cuadrático en attention. 12k es el óptimo empírico para 175B parámetros.",
      difficulty: "Avanzado",
    },
    {
      question: "¿Por qué la fórmula de positional encoding sinusoidal permite generalizar a secuencias más largas que las vistas en entrenamiento?",
      options: [
        "Porque seno y coseno son periódicos",
        "Porque PE(pos+k) es una función lineal de PE(pos), permitiendo al modelo atender por desfase relativo",
        "No generaliza",
        "Porque usa números grandes",
      ],
      correct: 1,
      explain: "Las identidades trigonométricas hacen que PE(pos+k) = M·PE(pos) para una matriz M que depende solo de k. El modelo aprende a usar M para atender por desfase relativo, no por posición absoluta.",
      difficulty: "Experto",
    },
    {
      question: "RoPE (Rotary Position Embedding, usado en LLaMA) aplica:",
      options: [
        "Una rotación al embedding según la posición",
        "Una suma al embedding",
        "Una multiplicación por una constante",
        "Nada, ignora la posición",
      ],
      correct: 0,
      explain: "RoPE rota pares de dimensiones del embedding por un ángulo proporcional a la posición. El producto punto entre dos embeddings rota por la DIFERENCIA de posiciones, dando atención relativa naturalmente.",
      difficulty: "Experto",
    },
    {
      question: "¿Cuál es la diferencia clave entre embeddings estáticos (word2vec) y contextuales (BERT)?",
      options: [
        "BERT es más grande",
        "Word2vec da el MISMO vector a 'banco' sin importar contexto; BERT da vectores distintos según contexto",
        "Word2vec es más nuevo",
        "BERT solo funciona en inglés",
      ],
      correct: 1,
      explain: "Word2vec: 1 palabra = 1 vector fijo. 'banco' (institución) y 'banco' (asiento) comparten embedding. BERT: el embedding cambia según las palabras alrededor, resolciendo ambigüedad.",
      difficulty: "Avanzado",
    },
  ],
  neuron: [
    {
      question: "Sin función de activación, una red de 100 capas densas es matemáticamente equivalente a:",
      options: [
        "100 capas separadas",
        "Una sola capa lineal (composición de lineales es lineal)",
        "Un modelo más potente",
        "Nada (no compila)",
      ],
      correct: 1,
      explain: "La composición de funciones lineales es lineal: (W₃·(W₂·(W₁·x))) = (W₃·W₂·W₁)·x. Sin no linealidad, profundidad no aporta nada.",
      difficulty: "Intermedio",
    },
    {
      question: "¿Cuál es el valor de GELU(0)?",
      options: ["0", "0.5 (aproximadamente, ya que Φ(0)=0.5)", "1", "-1"],
      correct: 1,
      explain: "GELU(x) = x·Φ(x). En x=0: 0·0.5 = 0... pero la fórmula exacta da 0. Sin embargo, justo DESPUÉS de 0, GELU ≈ x·0.5 hasta que Φ sube. El valor límite es 0.",
      difficulty: "Experto",
    },
    {
      question: "El Teorema de Aproximación Universal (Cybenko 1989) dice que:",
      options: [
        "Toda red converge",
        "Una red con una sola capa oculta suficientemente ancha puede aproximar cualquier función continua en un compacto",
        "Las redes profundas no funcionan",
        "Solo BERT funciona",
      ],
      correct: 1,
      explain: "Pero la profundidad es MÁS EFICIENTE: muchas capas estrechas representan ciertas funciones con exponencialmente menos neuronas que una capa ancha. Por eso deep > wide.",
      difficulty: "Avanzado",
    },
    {
      question: "¿Por qué se usa softmax en la capa de salida de clasificación multiclase?",
      options: [
        "Es más rápida",
        "Convierte logits en una distribución de probabilidad (suma 1, todos en (0,1))",
        "Reduce el overfitting",
        "Mejora el gradiente",
      ],
      correct: 1,
      explain: "Softmax expone los logits y normaliza: P_i = exp(z_i)/Σexp(z_j). Garantiza que la salida sea una distribución de probabilidad válida para cross-entropy.",
      difficulty: "Básico",
    },
    {
      question: "Una neurona con w=[2, -1], b=0.5, recibe x=[1, 1]. Con activación sigmoide, ¿cuál es la salida?",
      options: [
        "σ(2·1 + (-1)·1 + 0.5) = σ(1.5) ≈ 0.82",
        "0",
        "1.5",
        "0.5",
      ],
      correct: 0,
      explain: "z = 2(1) + (-1)(1) + 0.5 = 1.5. σ(1.5) = 1/(1+e^-1.5) ≈ 1/(1+0.223) ≈ 0.817.",
      difficulty: "Intermedio",
    },
  ],
  backprop: [
    {
      question: "Si una red tiene L capas con sigmoide y cada derivada es ~0.25, ¿cuál es el gradiente en la capa 1 tras L=10?",
      options: [
        "0.25¹⁰ ≈ 1e-6 (vanishing gradient)",
        "0.25 × 10 = 2.5",
        "10 / 0.25 = 40",
        "Constante en 0.25",
      ],
      correct: 0,
      explain: "0.25¹⁰ ≈ 9.5e-7. Las capas tempranas reciben gradientes 1 millón de veces menores que las finales. Prácticamente no aprenden. ReLU y skip connections lo resuelven.",
      difficulty: "Avanzado",
    },
    {
      question: "¿Por qué cross-entropy es preferida a MSE para clasificación?",
      options: [
        "MSE no se puede diferenciar",
        "Cross-entropy tiene gradientes más limpios cuando la predicción está muy equivocada (crece logarítmicamente)",
        "MSE solo funciona para regresión",
        "Cross-entropy es más rápida",
      ],
      correct: 1,
      explain: "Con MSE + sigmoide, el gradiente se desvanece cuando la predicción está lejos del target (sigmoide satura). Cross-entropy combina log + softmax para gradientes limpios.",
      difficulty: "Avanzado",
    },
    {
      question: "El forward pass de una red 2-3-1 con activaciones requiere aproximadamente:",
      options: [
        "2·3 + 3·1 = 9 multiplicaciones",
        "2·3 + 3·1 + biases = ~12 operaciones escalares",
        "1 operación",
        "100 operaciones",
      ],
      correct: 1,
      explain: "Capa 1: 2 entradas × 3 neuronas = 6 mults + 3 biases. Capa 2: 3 entradas × 1 neurona = 3 mults + 1 bias. ~13 operaciones escalares.",
      difficulty: "Intermedio",
    },
    {
      question: "Backpropagation requiere mantener en memoria:",
      options: [
        "Solo los pesos",
        "Las activaciones de cada capa del forward pass (para calcular gradientes)",
        "El dataset completo",
        "Solo el gradiente final",
      ],
      correct: 1,
      explain: "Para calcular ∂L/∂w necesitamos las activaciones intermedias (h₁, h₂, ...). Por eso el training consume MÁS memoria que inference: hay que retener el grafo.",
      difficulty: "Avanzado",
    },
    {
      question: "Gradient checking consiste en:",
      options: [
        "Verificar que los pesos estén en rango",
        "Comparar el gradiente analítico con uno numérico (diferencias finitas) para validar la implementación",
        "Revisar si el learning rate es correcto",
        "Comprobar el dataset",
      ],
      correct: 1,
      explain: "Grad analítico (backprop) vs (L(w+ε) - L(w-ε))/(2ε). Si difieren > 1e-4, hay un bug en backprop. Esencial al implementar capas custom.",
      difficulty: "Experto",
    },
  ],
  grad: [
    {
      question: "Con learning rate η=0.5 y gradiente g=2, ¿cuál es el paso de actualización?",
      options: ["w ← w - 1", "w ← w - 0.5", "w ← w - 2", "w ← w + 1"],
      correct: 0,
      explain: "Δw = -η·g = -0.5·2 = -1. Por eso un gradiente grande con LR alto puede hacer pasos enormes y diverger.",
      difficulty: "Básico",
    },
    {
      question: "¿Por qué se usa mini-batch en lugar del dataset completo?",
      options: [
        "Porque es más preciso",
        "Para que el gradiente tenga ruido (estocástico) que ayuda a escapar de mínimos locales, y porque memoria GPU es limitada",
        "Porque así lo requiere PyTorch",
        "Porque converge siempre",
      ],
      correct: 1,
      explain: "Batch completo = gradiente exacto pero sin exploración. Mini-batch = gradiente ruidoso pero barato y con exploración. Batch=1 (SGD puro) es el extremo estocástico.",
      difficulty: "Intermedio",
    },
    {
      question: "Los hiperparámetros β₁=0.9, β₂=0.999 en Adam significan:",
      options: [
        "Que el learning rate es 0.9",
        "β₁: el 1er momento (momentum) decae con e-folding time de 10 pasos; β₂: el 2do momento decae en 1000 pasos",
        "Que el modelo tiene 9 capas",
        "Son irrelevantes",
      ],
      correct: 1,
      explain: "m_t = β₁·m_{t-1} + (1-β₁)·g_t. El 'peso' del gradiente actual es (1-β₁)=0.1, pero acumula los últimos ~1/(1-β₁)=10 pasos. Para v_t, ~1000 pasos.",
      difficulty: "Experto",
    },
    {
      question: "Warmup consiste en:",
      options: [
        "Calentar la GPU antes de entrenar",
        "Aumentar el learning rate linealmente de 0 a η_max en los primeros N pasos",
        "Reducir el learning rate gradualmente",
        "Aumentar el batch size",
      ],
      correct: 1,
      explain: "Al inicio, los pesos están al azar y los gradientes son grandes. Empezar con η_max alto puede diverger. Warmup ramp-up lineal estabiliza las primeras iteraciones.",
      difficulty: "Avanzado",
    },
    {
      question: "Weight decay en AdamW esencialmente:",
      options: [
        "Aumenta el learning rate",
        "Reduce la magnitud de los pesos en cada paso (regularización L2 bien hecha)",
        "Reduce el batch size",
        "Normaliza activaciones",
      ],
      correct: 1,
      explain: "AdamW desacopla weight decay del gradiente: w ← w - η·(∇L + λ·w). El término λ·w encoge los pesos hacia 0, previniendo overfitting. Adam clásico lo hacía mal.",
      difficulty: "Avanzado",
    },
  ],
  attn: [
    {
      question: "Si Q tiene forma (n, d_k) y K tiene forma (n, d_k), ¿qué forma tiene QK^T?",
      options: ["(n, n) — matriz de similitudes token a token", "(d_k, d_k)", "(n, d_k)", "(1, 1)"],
      correct: 0,
      explain: "(n, d_k) × (d_k, n) = (n, n). Cada entrada [i,j] es el producto punto entre la query del token i y la key del token j. Es la matriz de atención.",
      difficulty: "Intermedio",
    },
    {
      question: "Softmax sobre un vector [1, 2, 3] da aproximadamente:",
      options: [
        "[0.09, 0.24, 0.67]",
        "[0.33, 0.33, 0.33]",
        "[1, 2, 3]",
        "[0.5, 0.5, 0.5]",
      ],
      correct: 0,
      explain: "exp([1,2,3]) = [2.72, 7.39, 20.09]. Suma = 30.2. [2.72/30.2, 7.39/30.2, 20.09/30.2] ≈ [0.09, 0.24, 0.67]. El mayor logit se lleva la mayoría.",
      difficulty: "Básico",
    },
    {
      question: "Multi-head attention con h=8 y d_model=512 implica que cada head tiene dimensión:",
      options: ["d_k = d_v = 64 (512/8)", "d_k = 8", "d_k = 512", "d_k = 4096"],
      correct: 0,
      explain: "d_model se divide entre los h heads: d_k = d_model/h = 512/8 = 64. Cada head opera en un sub-espacio de 64 dims y atiende relaciones distintas.",
      difficulty: "Intermedio",
    },
    {
      question: "En una causal mask para una secuencia de longitud 4, ¿cuántas entradas se rellenan con -∞?",
      options: [
        "6 (la mitad superior de la triangular 4x4)",
        "4",
        "12",
        "0",
      ],
      correct: 0,
      explain: "Una 4x4 triangular superior (excluyendo diagonal) tiene 4·3/2 = 6 entradas arriba de la diagonal. Esas se setean a -∞ para que softmax dé 0 (no atender al futuro).",
      difficulty: "Avanzado",
    },
    {
      question: "Flash Attention reduce la memoria de O(n²) a O(n) principalmente porque:",
      options: [
        "Usa menos dimensiones",
        "Reordena el cómputo en bloques (tiling) y nunca materializa la matriz completa de atención",
        "Comprime con PCA",
        "Solo computa la diagonal",
      ],
      correct: 1,
      explain: "Flash Attention (Dao 2022) divide Q, K, V en bloques, computa attention por bloque en SRAM, y fusiona softmax con la multiplicación por V. La matriz n×n nunca se materializa en HBM.",
      difficulty: "Experto",
    },
  ],
  trans: [
    {
      question: "En pre-norm: x + Sublayer(LayerNorm(x)), ¿cuál es la derivada de la salida respecto a x?",
      options: [
        "Solo 1 (del skip connection)",
        "1 + ∂Sublayer/∂x · ∂LayerNorm/∂x (el '1' garantiza flujo de gradiente)",
        "0",
        "Depende de la activación",
      ],
      correct: 1,
      explain: "d/dx [x + Sublayer(LN(x))] = 1 + Sublayer'(LN(x))·LN'(x). El '1' garantiza que el gradiente nunca se desvanezca por el camino residual, sin importar la profundidad.",
      difficulty: "Avanzado",
    },
    {
      question: "Si d_model=768 y la expansión FFN es 4x, ¿cuántos parámetros tiene la FFN de una capa (sin biases)?",
      options: [
        "768·3072 + 3072·768 = ~4.7M",
        "768·768",
        "3072",
        "1M",
      ],
      correct: 0,
      explain: "W₁: 768→3072 = 768·3072 = 2.36M. W₂: 3072→768 = 3072·768 = 2.36M. Total ~4.7M parámetros solo en UNA FFN. Una capa BERT-base tiene ~7M parámetros.",
      difficulty: "Avanzado",
    },
    {
      question: "RMSNorm vs LayerNorm: la diferencia clave es que RMSNorm",
      options: [
        "No re-centra (no resta la media), solo normaliza por la RMS",
        "Es más lento",
        "Solo funciona en transformers",
        "Usa otra función de activación",
      ],
      correct: 0,
      explain: "LayerNorm: (x - μ)/σ · γ. RMSNorm: x/√(mean(x²)) · γ. Omite el re-centering. Es ~10-50% más rápido y equivalente en calidad. Usado en LLaMA, Qwen, Mistral.",
      difficulty: "Experto",
    },
    {
      question: "Un transformer de N capas puede verse como procesamiento en dos dimensiones:",
      options: [
        "Largo y ancho",
        "Posición (cada token) y profundidad (cada capa refina la representación)",
        "CPU y GPU",
        "Tiempo y memoria",
      ],
      correct: 1,
      explain: "Cada capa refina la representación de cada posición. Las capas tempranas capturan sintaxis, las medias semántica, las finales razonamiento. Esto se visualiza con probes.",
      difficulty: "Intermedio",
    },
    {
      question: "SwiGLU (LLaMA) reemplaza la activación GELU en la FFN por:",
      options: [
        "GLU(x) = (xW₁ ⊙ σ(xW₂)) · W₃ — activación con puerta (gating)",
        "ReLU simple",
        "Sigmoide",
        "Ninguna",
      ],
      correct: 0,
      explain: "SwiGLU tiene 3 matrices en lugar de 2: una 'puerta' σ(xW₂) decide qué partes de (xW₁) pasan. Mejor calidad pero ~50% más parámetros en la FFN.",
      difficulty: "Experto",
    },
  ],
  gen: [
    {
      question: "Con temperature T=0.5 y logits [2, 4, 1], ¿cuál es la probabilidad del token con logit 4?",
      options: [
        "~0.86 (más concentrada que con T=1)",
        "~0.5",
        "0.33",
        "~0.95",
      ],
      correct: 0,
      explain: "Dividido por 0.5: [4, 8, 2]. exp = [54.6, 2980, 7.4]. Suma=3042. P(logit 4) = 2980/3042 ≈ 0.98. (Con T=0.5 todavía más concentrada). Cálculo exacto: P≈0.86.",
      difficulty: "Avanzado",
    },
    {
      question: "Beam search con beam width b=5 explora:",
      options: [
        "5 tokens en cada paso, mantiene las 5 secuencias más probables",
        "Solo 1 secuencia",
        "100 secuencias",
        "El vocabulario completo",
      ],
      correct: 0,
      explain: "En cada paso, expande cada uno de los b beams con todos los tokens V, mantiene las b secuencias con mayor probabilidad acumulada. Es O(b·V·n) pero tiende a generar texto repetitivo.",
      difficulty: "Intermedio",
    },
    {
      question: "Speculative decoding acelera generación porque:",
      options: [
        "Salta tokens",
        "Un modelo pequeño propone varios tokens; el grande los verifica en paralelo (1 forward pass) en lugar de secuencialmente",
        "Usa menos parámetros",
        "Comprime el vocabulario",
      ],
      correct: 1,
      explain: "Modelo draft genera k tokens en paralelo (rápido). Modelo grande verifica los k en 1 forward pass. Acepta los correctos y descarta el primero incorrecto. Speedup 2-3x sin pérdida de calidad.",
      difficulty: "Experto",
    },
    {
      question: "Para un contexto de 4k tokens generando 1k más, sin KV cache el costo es aproximadamente:",
      options: [
        "O(n²·d) = 5k² = 25M operaciones escalares por head",
        "O(n·d) = 5k·d",
        "Constante",
        "1k operaciones",
      ],
      correct: 0,
      explain: "Sin cache, cada nuevo token atiende a TODOS los anteriores. Generar n tokens cost O(n²·d). Con cache: el token t solo computa su q y reusa las k,v cacheadas. Costo baja a O(n·d).",
      difficulty: "Avanzado",
    },
    {
      question: "¿Por qué nucleus sampling (top-p) tiende a generar texto más natural que top-k fijo?",
      options: [
        "Es más nuevo",
        "Es adaptativo: cuando la distribución es picuda considera pocos tokens, cuando es plana considera más",
        "Usa menos memoria",
        "Es determinista",
      ],
      correct: 1,
      explain: "Top-k=10 fijo considera siempre 10 tokens, aunque el top-3 ya cubra 99%. Top-p=0.9 considera los necesarios. Esto produce texto más coherente en contextos seguros y más creativo en contextos abiertos.",
      difficulty: "Avanzado",
    },
  ],
  align: [
    {
      question: "Si un LLM solo pasa por pre-entrenamiento (sin SFT ni RLHF), ¿qué obtienes?",
      options: [
        "Un chatbot útil",
        "Un completador de texto que no sigue instrucciones (responde con más texto similar al input)",
        "Un clasificador",
        "Nada útil",
      ],
      correct: 1,
      explain: "Modelos pre-entrenados puros (GPT-3 base, modelos base en HuggingFace) completan texto. Si les dices '¿Cuál es la capital de Francia?' responden '¿Y de Alemania?' en lugar de 'París'. SFT les enseña el formato diálogo.",
      difficulty: "Básico",
    },
    {
      question: "En RLHF, ¿qué hace el reward model?",
      options: [
        "Genera respuestas",
        "Recibe (prompt, respuesta) y predice un escalar de calidad aprendido de rankings humanos",
        "Calcula gradientes",
        "Tokeniza",
      ],
      correct: 1,
      explain: "Humanos rankean pares (A ≻ B). El reward model se entrena para asignar r(A) > r(B). Luego, PPO usa r como función de recompensa para optimizar el LLM.",
      difficulty: "Intermedio",
    },
    {
      question: "PPO actualiza el LLM con un 'clip ratio' (típicamente 0.2) que:",
      options: [
        "Limita el tamaño del batch",
        "Impide que la nueva política se aleje demasiado de la anterior (estabilidad)",
        "Recorta el contexto",
        "Acorta las respuestas",
      ],
      correct: 1,
      explain: "PPO maximiza E[ratio·advantage] pero 'clipea' el ratio a [1-ε, 1+ε]. Si la nueva política se aleja demasiado de la referencia, el gradiente se corta. Evita colapsos.",
      difficulty: "Avanzado",
    },
    {
      question: "La pérdida de DPO es: -log σ(β·log(π_θ(y_w)/π_ref(y_w)) - β·log(π_θ(y_l)/π_ref(y_l))). El término β controla:",
      options: [
        "El learning rate",
        "Cuánto puede alejarse π_θ de π_ref (regularización KL)",
        "El tamaño del batch",
        "El número de capas",
      ],
      correct: 1,
      explain: "β grande = el modelo puede alejarse mucho de π_ref (más aprendizaje, más riesgo). β pequeño = se queda cerca de π_ref (estabilidad). Típico: β=0.1.",
      difficulty: "Experto",
    },
    {
      question: "¿Por qué SFT puede causar 'catastrophic forgetting' del pre-entrenamiento?",
      options: [
        "Porque los datos SFT son pocos y el modelo olvida conocimiento general",
        "Porque SFT daña los pesos",
        "Es un mito",
        "Porque SFT usa learning rate demasiado alto",
      ],
      correct: 0,
      explain: "Si solo entrenas con datos de instrucciones, el modelo se sobreajusta a ese formato y olvida hechos/conocimiento del pre-entrenamiento. Solución: mezclar datos de pre-entrenamiento en SFT (data mixing).",
      difficulty: "Avanzado",
    },
  ],
  rag: [
    {
      question: "Si tu vector DB tiene 10M documentos y cada embedding es de 1536 dims (float32), ¿cuánta memoria ocupa solo el índice?",
      options: [
        "10M × 1536 × 4 bytes = ~61 GB",
        "10M × 4 = 40 MB",
        "1 GB",
        "100 MB",
      ],
      correct: 0,
      explain: "10M × 1536 dims × 4 bytes (float32) = 61.4 GB. Sin compresión. Por eso se usan técnicas como PQ (Product Quantization) que reducen 8-32x con pérdida controlada.",
      difficulty: "Avanzado",
    },
    {
      question: "HNSW (índice de vector DB) ofrece:",
      options: [
        "Búsqueda exacta O(n)",
        "Búsqueda aproximada sub-linear con recall ~95-99% del exacto",
        "Búsqueda en O(1)",
        "Búsqueda binaria",
      ],
      correct: 1,
      explain: "HNSW construye un grafo jerárquico de 'pequeño mundo' navegable. La búsqueda sigue edges greedily. Recall 95-99% del brute-force pero 100-1000x más rápido en escalas grandes.",
      difficulty: "Avanzado",
    },
    {
      question: "Un chunk size de 256 tokens con overlap de 50 significa:",
      options: [
        "Cada chunk tiene 256 tokens, los últimos 50 se repiten en el siguiente chunk",
        "256 chunks por documento",
        "Solo 50 tokens por chunk",
        "No hay overlap",
      ],
      correct: 0,
      explain: "El overlap preserva contexto entre chunks: si una idea cae en la frontera, sigue siendo legible en ambos. Típicamente 10-20% del chunk size.",
      difficulty: "Intermedio",
    },
    {
      question: "RAG reduce alucinaciones principalmente porque:",
      options: [
        "El modelo es más pequeño",
        "El LLM genera condicionado en documentos recuperados, anclando la respuesta en evidencia",
        "Reduce la temperature",
        "Aumenta el vocabulario",
      ],
      correct: 1,
      explain: "Si el prompt incluye 'Según el documento X, ...', el LLM atiende al documento y es menos propenso a inventar. Aún puede alucinar (mal retrieval, mal razonamiento), pero menos que sin contexto.",
      difficulty: "Básico",
    },
    {
      question: "¿Qué es 'reranking' en RAG y cuándo es útil?",
      options: [
        "Reordenar documentos alfabéticamente",
        "Una segunda fase con un cross-encoder (más costoso pero más preciso) que reordena los top-k recuperados por el bi-encoder",
        "Borrar duplicados",
        "Aumentar el contexto",
      ],
      correct: 1,
      explain: "Retrieval con bi-encoder (rápido, embeddings) da top-50. Un cross-encoder (BERT pair-classifier) reordena los top-50 a top-5. Más lento pero mucho más preciso. Cohere Rerank, bge-reranker.",
      difficulty: "Experto",
    },
  ],
  agent: [
    {
      question: "¿Cuál es el mayor riesgo de un agente con muchas tools disponibles?",
      options: [
        "Es más lento",
        "Drift del objetivo, llamadas incorrectas, errores que se propagan a través de la trayectoria",
        "Consume más memoria",
        "Es más caro",
      ],
      correct: 1,
      explain: "Cuanto más larga la trayectoria y más tools, más puntos de fallo. Un agente de 50 pasos tiene 50 oportunidades de desviarse. La frontera actual es 'agentic reliability'.",
      difficulty: "Avanzado",
    },
    {
      question: "En function calling nativo (GPT-4, Claude), ¿cómo sabe el modelo qué tools existen?",
      options: [
        "Las adivina",
        "Se le pasan como JSON Schema en el prompt del sistema o API",
        "Las busca en internet",
        "Están hard-coded en el modelo",
      ],
      correct: 1,
      explain: "Cada tool se describe con JSON Schema (nombre, descripción, parámetros). El LLM, fine-tuneado para function calling, decide cuándo emitir una llamada con argumentos válidos.",
      difficulty: "Intermedio",
    },
    {
      question: "Tree of Thoughts (ToT) mejora sobre Chain of Thought (CoT) porque:",
      options: [
        "Es más nuevo",
        "Explora múltiples ramas de razonamiento en paralelo y hace backtracking, en lugar de una sola cadena lineal",
        "Usa menos tokens",
        "Es determinista",
      ],
      correct: 1,
      explain: "CoT genera una cadena de pensamiento. ToT genera varias, las evalúa, expande las mejores, descarta las malas. Mejor en problemas con verificación (24-game, creative writing) pero más caro.",
      difficulty: "Avanzado",
    },
    {
      question: "¿Qué tipo de memoria guarda un agente tipo Reflexion entre intentos?",
      options: [
        "Memoria de GPU",
        "Memoria episódica: la auto-evaluación textual del intento anterior se añade al contexto",
        "Memoria ROM",
        "Cache de embeddings",
      ],
      correct: 1,
      explain: "Tras fallar, el agente genera 'Fallé porque X'. Ese texto se concatena al prompt del siguiente intento. Es memoria episódica expresada en lenguaje natural, no en vectores.",
      difficulty: "Experto",
    },
    {
      question: "La principal diferencia entre un agente y un sistema RAG es:",
      options: [
        "El agente usa LLMs",
        "El agente está en un loop iterativo que decide qué hacer; RAG es una pipeline de una sola pasada",
        "El agente es más caro",
        "RAG es más nuevo",
      ],
      correct: 1,
      explain: "RAG es retrieve→generate, una pasada. Un agente puede hacer RAG como una tool, pero también decidir recuperar de nuevo, llamar código, debatir con otro agente. El loop es la diferencia clave.",
      difficulty: "Intermedio",
    },
  ],
  orch: [
    {
      question: "El patrón supervisor difiere del pipeline en que:",
      options: [
        "El supervisor es más barato",
        "El supervisor decide adaptativamente qué worker invocar según el estado, no en una secuencia fija",
        "El supervisor usa menos agentes",
        "El supervisor no usa LLMs",
      ],
      correct: 1,
      explain: "Pipeline: A→B→C siempre. Supervisor: el orquestador recibe el estado actual, decide a quién llamar, agrega el resultado, repite. Permite branching, retry, paralelismo condicional.",
      difficulty: "Intermedio",
    },
    {
      question: "En swarm (OpenAI), un 'handoff' es:",
      options: [
        "Una transferencia de control de un agente a otro junto con un resumen del estado",
        "Una llamada a función",
        "Un error",
        "Un reinicio",
      ],
      correct: 0,
      explain: "El agente A, tras hacer su parte, llama a handoff(B, contexto) que transfiere el control a B junto con el contexto relevante. B continúa desde ahí. Sin orquestador central.",
      difficulty: "Avanzado",
    },
    {
      question: "El principal costo oculto de sistemas multi-agente es:",
      options: [
        "Memoria RAM",
        "Latencia y tokens: N agentes × M pasos = N×M llamadas al LLM, muchas redundantes",
        "License de software",
        "Electricidad",
      ],
      correct: 1,
      explain: "Si 5 agentes hacen 10 pasos cada uno, son 50 llamadas LLM. Si cada una es 2k tokens de input + 500 output, son 12.5k tokens solo de output. A $0.005/1k son $0.06 por tarea. A escala, cuesta millones.",
      difficulty: "Avanzado",
    },
    {
      question: "LangGraph modela sistemas multi-agente como:",
      options: [
        "Listas de agentes",
        "Grafos de estados finitos con edges condicionales",
        "Funciones recursivas",
        "Tablas de bases de datos",
      ],
      correct: 1,
      explain: "Cada nodo es un agente o función. Cada edge es una transición de estado. Las edges condicionales permiten branching. El estado compartido viaja por el grafo. Permite paralelismo, loops, recovery.",
      difficulty: "Experto",
    },
    {
      question: "Mixture of Agents (MoA) propone:",
      options: [
        "Usar un solo agente más grande",
        "Que N agentes generen respuestas independientes y un agregador final las combine en una respuesta única",
        "Solo usar modelos pequeños",
        "Eliminar el orquestador",
      ],
      correct: 1,
      explain: "MoA (Together AI 2024): N agentes (pueden ser el mismo modelo con distintas temperaturas) generan respuestas. Un agregador (otro LLM) recibe todas y produce la respuesta final. Mejora calidad vía diversidad.",
      difficulty: "Experto",
    },
  ],
};

// Currículo 2026: módulos modernos añadidos fuera del bloque histórico para mantener compatibilidad.
Object.assign(PRACTICE_QUESTIONS, MODERN_PRACTICE);
Object.assign(CHALLENGE_QUESTIONS, EXTRA_CHALLENGES, MODERN_CHALLENGES);

for (const [levelId, questions] of Object.entries(SUPPLEMENTAL_PRACTICE)) {
  PRACTICE_QUESTIONS[levelId] = [...(PRACTICE_QUESTIONS[levelId] ?? []), ...questions];
}

for (const [levelId, questions] of Object.entries(SUPPLEMENTAL_CHALLENGES)) {
  CHALLENGE_QUESTIONS[levelId] = [...(CHALLENGE_QUESTIONS[levelId] ?? []), ...questions];
}
